import test from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {createTestDatabase} from './database.mjs';
async function moduleAt(path){const out=await build({entryPoints:[path],bundle:true,write:false,platform:'node',format:'esm'});return import(`data:text/javascript;base64,${Buffer.from(out.outputFiles[0].text).toString('base64')}`);}
const {summarizeHealth}=await moduleAt('lib/health-insights.ts');
const {journalAction,journalPage,healthDashboard}=await moduleAt('lib/training-journal.ts');
const sample=(date,content,updatedAt=1)=>({id:crypto.randomUUID(),date,content,updatedAt,revision:1});
const body=weight=>({kind:'body',weight,fat:null,muscle:null,note:''});
test('period comparison uses latest daily measurement and does not fill missing days',()=>{const data=[sample('2026-09-22',body(80),1),sample('2026-09-22',body(82),2),sample('2026-09-20',body(80)),sample('2026-09-12',body(84)),sample('2026-09-13',body(86)),sample('2026-09-23',body(1))];const x=summarizeHealth(data,'2026-09-22',7);assert.equal(x.weight.points.length,2);assert.equal(x.weight.average,81);assert.equal(x.weight.previousAverage,85);assert.equal(x.weight.delta,-4);assert.equal(x.todayKinds.length,1);assert.equal(summarizeHealth(data.slice(0,2),'2026-09-22',7).weight.delta,null);});
test('nutrition completeness distinguishes explicit zero from absent measurements',()=>{const base={kind:'meal',name:'식사',meal:'lunch',note:'',calories:0,protein:0,carbs:0,fat:0};const x=summarizeHealth([sample('2026-09-22',base),sample('2026-09-22',{...base,protein:null}),sample('2026-09-20',{kind:'cardio',name:'걷기',minutes:30,distance:null,note:''}),sample('2026-09-21',{kind:'recovery',sleep:7,energy:null,soreness:null,note:''})],'2026-09-22',7);assert.equal(x.nutrition.complete,1);assert.equal(x.nutrition.missing,1);assert.equal(x.nutrition.days,1);assert.equal(x.cardio.minutes,30);assert.equal(x.sleep.average,7);assert.equal(x.sleep.delta,null);});
test('kind-filtered history is private and dashboard timeline omits journal notes',async()=>{const f=await createTestDatabase();try{for(const [who,content] of [['a',body(80)],['a',{kind:'meal',name:'private food',meal:'lunch',note:'private note',calories:100,protein:1,carbs:2,fat:3}],['b',body(99)]])await journalAction(f.db,who,{action:'save',entry:{id:crypto.randomUUID(),revision:0,date:'2026-09-22',content}});const page=await journalPage(f.db,'a',null,'body');assert.equal(page.entries.length,1);assert.equal(page.entries[0].content.weight,80);await assert.rejects(journalPage(f.db,'a',null,'invalid'));const d=await healthDashboard(f.db,'a',Date.parse('2026-09-22T04:00:00Z'));assert.equal(d.timeline.length,2);assert.ok(d.timeline.every(e=>e.content.note===''));assert.equal(d.timeline.find(e=>e.content.kind==='meal').content.name,'');}finally{await f.close();}});
