import test from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {createTestDatabase} from './database.mjs';
async function moduleAt(path){const out=await build({entryPoints:[path],bundle:true,write:false,platform:'node',format:'esm'});return import(`data:text/javascript;base64,${Buffer.from(out.outputFiles[0].text).toString('base64')}`);}
const {applyToRemaining,repeatState,nextPlanItems}=await moduleAt('lib/training-next-plan.ts');
const {nextWorkoutPlan,trainingAction}=await moduleAt('lib/training-service.ts');
const profile={goal:'hypertrophy',experience:'intermediate',daysPerWeek:3,adult:true};
const set=(id,patch={})=>({id,kind:'working',weight:50,reps:10,seconds:null,rir:2,done:true,...patch});
function history(){return [0,1,2].map(i=>({id:crypto.randomUUID(),user_id:'u',crew_id:'c',routine_id:'r',routine_name:'Bench',status:'completed',revision:1,started_at:Date.now()-(i+1)*86400000-3600000,finished_at:Date.now()-(i+1)*86400000,updated_at:Date.now(),state:{restSeconds:90,note:'old',discomfort:'none',conditionsConfirmed:true,durationMinutes:60,exercises:[{id:'e',name:'벤치프레스',plannedReps:10,timed:false,convention:'total',equipmentLabel:'bar',prescription:'',sets:[set('s1'),set('s2')]}]}}));}
test('bulk values preserve completed sets, different set kinds, ids and subjective effort',()=>{const e=history()[0].state.exercises[0];e.sets=[set('source',{done:false,weight:55,reps:11}),set('finished'),set('pending',{done:false,rir:3}),set('warmup',{done:false,kind:'warmup',weight:20})];const result=applyToRemaining(e,'source');assert.deepEqual(result.sets[1],e.sets[1]);assert.deepEqual(result.sets[3],e.sets[3]);assert.equal(result.sets[2].id,'pending');assert.equal(result.sets[2].weight,55);assert.equal(result.sets[2].reps,11);assert.equal(result.sets[2].rir,null);assert.equal(result.sets[2].done,false);assert.equal(e.sets[2].weight,50);});
test('next plan adds one rep only on eligible recent comparable ordinary sets',()=>{const h=history(),items=nextPlanItems(h[0],h,profile);assert.equal(items[0].status,'progress');assert.equal(items[0].sets[0].to,11);const state=repeatState(h[0],items);assert.equal(state.exercises[0].sets[0].weight,50);assert.equal(state.exercises[0].sets[0].reps,11);assert.equal(state.exercises[0].sets[0].done,false);assert.equal(state.exercises[0].sets[0].rir,null);assert.equal(state.conditionsConfirmed,false);assert.equal(state.durationMinutes,undefined);assert.equal(state.exercises[0].plannedReps,11);assert.equal(h[0].state.exercises[0].sets[0].reps,10);
 for(const mutate of [x=>x[0].state.discomfort='yes',x=>x[0].state.exercises[0].superset='A',x=>x[0].state.exercises[0].sets[1].done=false,x=>x[0].state.exercises[0].sets.forEach(s=>s.reps=20)]){const copy=structuredClone(h);mutate(copy);const p=nextPlanItems(copy[0],copy,profile);assert.notEqual(p[0].status,'progress');assert.equal(p[0].sets[0].to,copy[0].state.exercises[0].sets[0].reps);}
 assert.notEqual(nextPlanItems(h[1],h,profile)[0].status,'progress');assert.notEqual(nextPlanItems(h[0],h,null)[0].status,'progress');});
test('repeat preserves unperformed planned sets without manufacturing completion',()=>{const source=history()[0];source.state.exercises[0].sets[1].done=false;const next=repeatState(source);assert.equal(next.exercises[0].sets.length,2);assert.ok(next.exercises[0].sets.every(s=>!s.done&&s.rir===null));});
test('plan read is private and applying stale profile or record revisions is rejected atomically',async()=>{const f=await createTestDatabase();try{const h=history();for(const w of h)await f.db.prepare("INSERT INTO workout_sessions(id,user_id,crew_id,routine_id,routine_name,status,state,started_at,finished_at,updated_at) VALUES(?,?,?,?,?,'completed',?,?,?,?)").bind(w.id,'u','c','r','Bench',JSON.stringify(w.state),w.started_at,w.finished_at,w.updated_at).run();await trainingAction(f.db,'u',{action:'profile',profile});const plan=await nextWorkoutPlan(f.db,'u',h[0].id);assert.equal(plan.items[0].status,'progress');await assert.rejects(nextWorkoutPlan(f.db,'other',h[0].id),e=>e.status===404);await trainingAction(f.db,'u',{action:'profile',profile:{...profile,goal:'consistency'}});await assert.rejects(trainingAction(f.db,'u',{action:'repeat',id:crypto.randomUUID(),sourceId:h[0].id,planToken:plan.token}),e=>e.status===409);assert.equal((await f.db.prepare("SELECT count(*)::int AS n FROM workout_sessions WHERE status='active'").first()).n,0);await trainingAction(f.db,'u',{action:'profile',profile});const fresh=await nextWorkoutPlan(f.db,'u',h[0].id);const result=await trainingAction(f.db,'u',{action:'repeat',id:crypto.randomUUID(),sourceId:h[0].id,planToken:fresh.token});assert.equal(result.workout.state.exercises[0].sets[0].reps,11);assert.equal(result.workout.state.exercises[0].sets[0].done,false);assert.equal(result.workout.state.planBasis.token,fresh.token);const fake=structuredClone(result.workout.state);fake.planBasis.token='0'.repeat(64);const saved=await trainingAction(f.db,'u',{action:'save',id:result.workout.id,revision:result.workout.revision,state:fake});assert.equal(saved.workout.state.planBasis.token,fresh.token);assert.equal((await f.db.prepare('SELECT count(*)::int AS n FROM checkins').first()).n,0);}finally{await f.close();}});
