import test from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {createTestDatabase} from './database.mjs';
async function moduleAt(path){const out=await build({entryPoints:[path],bundle:true,write:false,platform:'node',format:'esm'});return import(`data:text/javascript;base64,${Buffer.from(out.outputFiles[0].text).toString('base64')}`);}
const {questionAction,questionPage}=await moduleAt('lib/training-community.ts');
const {buildTrainingProgram}=await moduleAt('lib/training-programs.ts');
const {journalAction,journalPage}=await moduleAt('lib/training-journal.ts');
const {restoreTraining,exportTraining}=await moduleAt('lib/training-backup.ts');
const {trainingAction,workoutHistory}=await moduleAt('lib/training-service.ts');
const {referenceMax,estimateMax,trainingInsights,platePlan,intervalState}=await moduleAt('lib/training-insights.ts');
const body=(id=crypto.randomUUID())=>({id,date:'2026-09-01',revision:0,content:{kind:'body',weight:80,fat:null,muscle:null,note:''}});
function workout(){return {id:crypto.randomUUID(),user_id:'a',crew_id:'c',routine_id:'r',routine_name:'Bench',status:'completed',revision:1,started_at:Date.now()-3600000,finished_at:Date.now()-1000,updated_at:Date.now(),state:{restSeconds:90,note:'unique-note',discomfort:'none',conditionsConfirmed:true,exercises:[{id:'b',name:'벤치프레스',plannedReps:5,timed:false,convention:'total',equipmentLabel:'bar',prescription:'',sets:[{id:'s',kind:'working',weight:100,reps:5,seconds:null,rir:0,done:true}]}]}};}
test('journal ownership, optimistic revision and reversible hiding',async()=>{const f=await createTestDatabase();try{const e=body();const saved=await journalAction(f.db,'a',{action:'save',entry:e});assert.equal(saved.entry.revision,1);assert.equal((await journalPage(f.db,'b')).entries.length,0);await assert.rejects(journalAction(f.db,'b',{action:'save',entry:{...e,revision:1}}),x=>x.status===404);await assert.rejects(journalAction(f.db,'a',{action:'save',entry:e}),x=>x.status===409);await assert.rejects(journalAction(f.db,'a',{action:'save',entry:{...body(),date:'2026-02-30'}}));await assert.rejects(journalAction(f.db,'a',{action:'save',entry:{...body(),content:{...e.content,fat:101}}}));const hidden=await journalAction(f.db,'a',{action:'archive',id:e.id,revision:1});assert.equal((await journalPage(f.db,'a')).entries.length,0);await journalAction(f.db,'a',{action:'restore',...hidden});assert.equal((await journalPage(f.db,'a')).entries[0].content.weight,80);}finally{await f.close();}});
test('backup is private, retry safe and foreign-ID failure rolls back entire batch',async()=>{const f=await createTestDatabase();try{const w=workout(),entry=body(),batch={format:'spot-training-v1',workouts:[w],journal:[entry]};assert.equal((await restoreTraining(f.db,'a',batch)).added,2);assert.equal((await restoreTraining(f.db,'a',batch)).skipped,2);assert.equal((await exportTraining(f.db,'b')).workouts.length,0);assert.equal((await exportTraining(f.db,'a')).workouts[0].state.note,'unique-note');const fresh=workout();await assert.rejects(restoreTraining(f.db,'b',{...batch,workouts:[fresh,w],journal:[]}),x=>x.status===403);assert.equal((await exportTraining(f.db,'b')).workouts.length,0);assert.equal((await workoutHistory(f.db,'a',null,'unique-note')).history.length,1);assert.equal((await workoutHistory(f.db,'a',null,'missing')).history.length,0);assert.equal((await workoutHistory(f.db,'a',null,"% OR 1=1")).history.length,0);const replay=await trainingAction(f.db,'a',{action:'repeat',id:crypto.randomUUID(),sourceId:w.id});assert.equal(replay.workout.state.exercises[0].sets[0].weight,100);assert.equal(replay.workout.state.exercises[0].sets[0].done,false);assert.equal(replay.workout.state.exercises[0].sets[0].rir,null);assert.equal(replay.workout.state.conditionsConfirmed,false);assert.equal((await f.db.prepare('SELECT count(*)::int AS n FROM checkins').first()).n,0);}finally{await f.close();}});
test('strength estimates abstain for missing effort, machines, high reps, timed sets and pain',()=>{const w=workout(),e=w.state.exercises[0],s=e.sets[0];assert.deepEqual(estimateMax(e,s),{low:112.5,high:116.7,measured:false});for(const patch of [{rir:null},{reps:11},{weight:null},{kind:'warmup'},{done:false}])assert.equal(estimateMax(e,{...s,...patch}),null);assert.equal(estimateMax({...e,convention:'machine'},s),null);assert.equal(estimateMax({...e,timed:true},s),null);w.state.discomfort='yes';assert.equal(trainingInsights([w]).records[0].estimate,null);assert.equal(trainingInsights([w]).total,null);});
test('big three never count variants or predicted max as measured total',()=>{const w=workout();w.state.exercises=['바벨 스쿼트','벤치프레스','컨벤셔널 데드리프트'].map((name,i)=>({...w.state.exercises[0],id:String(i),name,sets:[{...w.state.exercises[0].sets[0],reps:1,weight:100+i*20}]}));assert.equal(trainingInsights([w]).total,360);w.state.exercises[0].name='스미스 스쿼트';assert.equal(trainingInsights([w]).total,null);});
test('plate solver honors inventory and finds non-greedy combination; interval resumes by elapsed time',()=>{assert.deepEqual(platePlan(60,20,[{weight:20,pairs:1}]),{actual:60,exact:true,side:[{weight:20,count:1}]});const p=platePlan(12,0,[{weight:4,pairs:1},{weight:3,pairs:2}]);assert.equal(p.exact,true);assert.equal(p.side[0].weight,3);assert.equal(platePlan(61,20,[{weight:20,pairs:1}]).actual,60);assert.throws(()=>platePlan(10,20,[]));assert.deepEqual(intervalState(1000,31000,30,15,2),{phase:'rest',round:1,remaining:15});assert.deepEqual(intervalState(1000,76000,30,15,2),{phase:'done',round:2,remaining:0});});

test('Q&A requires explicit publishing, restricts edits and keeps report identities private',async()=>{const f=await createTestDatabase();try{const a={userId:'a',displayName:'Alice'},b={userId:'b',displayName:'Bob'},id=crypto.randomUUID();const post={action:'post',id,parent:null,body:'운동 순서를 어떻게 바꿔요?',publishConfirmed:true};await assert.rejects(questionAction(f.db,a,{...post,publishConfirmed:false}));await questionAction(f.db,a,post);await questionAction(f.db,a,post);const page=await questionPage(f.db,b.userId);assert.equal(page.items.length,1);assert.equal(page.items[0].mine,false);assert.equal('user_id'in page.items[0],false);await assert.rejects(questionAction(f.db,b,{action:'edit',id,revision:1,body:'내용을 바꿉니다.'}),e=>e.status===403);await questionAction(f.db,b,{action:'report',id});await questionAction(f.db,b,{action:'report',id});assert.equal((await questionPage(f.db,b.userId)).items[0].reports,0);await questionAction(f.db,b,{...post,id:crypto.randomUUID(),parent:id,body:'운동 구성에서 순서를 바꿀 수 있어요.'});assert.equal((await questionPage(f.db,a.userId,id)).items.length,1);await questionAction(f.db,a,{action:'hide',id,revision:1});await assert.rejects(questionPage(f.db,b.userId,id),e=>e.status===404);await assert.rejects(questionAction(f.db,b,{...post,id:crypto.randomUUID(),parent:id}),e=>e.status===404);}finally{await f.close();}});
test('program drafts are independent, match equipment constraints and retain timed units',()=>{const options={split:'fullbody',goal:'consistency',equipment:'home',experience:'beginner'};const a=buildTrainingProgram(options),b=buildTrainingProgram(options);assert.equal(a.length,2);assert.notEqual(a[0].id,b[0].id);assert.ok(a.flatMap(r=>r.exercises).every(e=>e.sets===2&&!/머신|케이블|레그 프레스/.test(e.name)));assert.equal(a[0].exercises.at(-1).durationSeconds,30);});

test('live intensity reference never crosses equipment identity or uses stale or unconfirmed records',()=>{const w=workout(),e=w.state.exercises[0];assert.equal(referenceMax([w],e).low,112.5);assert.equal(referenceMax([w],{...e,equipmentLabel:'other'}),undefined);w.state.conditionsConfirmed=false;assert.equal(referenceMax([w],e),undefined);w.state.conditionsConfirmed=true;w.finished_at=Date.now()-91*86400000;assert.equal(referenceMax([w],e),undefined);});
