 'use client';
import {useState} from 'react';
import type {HealthSample} from '@/lib/health-insights';
import {summarizeHealth} from '@/lib/health-insights';
function Sparkline({points,unit}:{points:{date:string;value:number}[];unit:string}){
 if(points.length<2)return <div className="health-chart-empty">서로 다른 날의 기록이 2개 모이면 추세를 보여드려요.</div>;
 const min=Math.min(...points.map(p=>p.value)),max=Math.max(...points.map(p=>p.value)),range=max-min||1;
 const first=Date.parse(points[0].date+'T00:00:00Z'),last=Date.parse(points.at(-1)!.date+'T00:00:00Z');
 const coords=points.map(p=>({x:12+(Date.parse(p.date+'T00:00:00Z')-first)/Math.max(1,last-first)*336,y:85-(p.value-min)/range*64,...p}));
 return <><svg className="health-sparkline" viewBox="0 0 360 106" role="img" aria-label={`${points.length}일 측정 추세, ${points[0].value}${unit}에서 ${points.at(-1)!.value}${unit}`}><path d="M12 86H348" stroke="currentColor" opacity=".12"/><polyline points={coords.map(p=>`${p.x},${p.y}`).join(' ')} fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinejoin="round"/>{coords.map(p=><circle key={p.date} cx={p.x} cy={p.y} r="3" fill="currentColor"><title>{p.date}: {p.value}{unit}</title></circle>)}</svg><div className="health-chart-dates"><span>{points[0].date.slice(5)}</span><span>{points.at(-1)!.date.slice(5)}</span></div></>;
}
export function HealthTrends({entries,today,truncated}:{entries:HealthSample[];today:string;truncated:boolean}){
 const [days,setDays]=useState(28),[metric,setMetric]=useState<'weight'|'sleep'>('weight');const summary=summarizeHealth(entries,today,days),trend=summary[metric],unit=metric==='weight'?'kg':'시간';
 return <section className="health-trend-panel"><div className="health-panel-heading"><h2>기록이 보여주는 변화</h2><div className="health-period" aria-label="추세 기간">{[7,28,90].map(n=><button key={n} aria-pressed={days===n} onClick={()=>setDays(n)}>{n}일</button>)}</div></div><div className="health-trend-layout"><div><div className="health-metric-switch" aria-label="추세 항목"><button aria-pressed={metric==='weight'} onClick={()=>setMetric('weight')}>체중</button><button aria-pressed={metric==='sleep'} onClick={()=>setMetric('sleep')}>수면</button></div><div className="health-trend-value"><strong>{trend.average??'—'}</strong><span>{unit} 평균</span></div><p className="health-caption">{trend.points.length}일 측정 · {trend.delta===null?'이전 기간과 비교할 기록이 아직 부족해요.':`이전 ${days}일 평균보다 ${trend.delta>0?'+':''}${trend.delta}${unit}`}</p><Sparkline points={trend.points} unit={unit}/><p className="health-caption">같은 날 여러 기록은 최근 수정 기록을 사용해요. 미기록 날짜는 평균에서 제외합니다.</p></div><div className="health-insight-stack"><article><span>식단 기록</span><strong>{summary.nutrition.days}<small>일</small></strong><p>{summary.nutrition.entries?`${summary.nutrition.entries}건 중 ${summary.nutrition.complete}건에 열량과 3대 영양소를 모두 입력했어요.`:'이 기간에 입력한 식단이 없어요.'}</p>{summary.nutrition.missing>0&&<small>영양표 확인이 필요한 기록 {summary.nutrition.missing}건</small>}</article><article><span>유산소 기록</span><strong>{summary.cardio.entries?summary.cardio.minutes:'—'}<small>분</small></strong><p>{summary.cardio.entries}건에 입력한 운동 시간이에요.</p></article></div></div>{truncated&&<p className="health-caption">최근 180일 중 최대 4,000건을 불러왔어요. 누락된 기간이 있을 수 있습니다.</p>}<details className="health-method"><summary>집계 기준</summary><p>비교는 각 기간에 서로 다른 날의 측정이 2개 이상 있을 때 표시합니다. 증가·감소를 좋고 나쁨으로 판정하지 않아요. 식단 입력 항목의 완성도는 실제 섭취량이나 건강 점수가 아닙니다.</p><div className="training-table-scroll"><table><thead><tr><th>측정일</th><th>{metric==='weight'?'체중 kg':'수면 시간'}</th></tr></thead><tbody>{trend.points.map(p=><tr key={p.date}><td>{p.date}</td><td>{p.value}</td></tr>)}</tbody></table></div></details></section>;
}
