'use client';
import {CoffeeResult} from './coffee-result';
import {useCallback,useEffect,useState} from 'react';
import {Check,Flag,Plus} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {localDate,addDays,type Crew} from '@/lib/gym-model';
import {sessionStart} from '@/lib/planning';
import type {Checkin,Mission} from '@/lib/missions';
import './crew-activity.css';
export function CrewActivity({crew,userId}:{crew:Crew;userId:string}){
 const [data,setData]=useState<{checkins:Checkin[];missions:Mission[]}>({checkins:[],missions:[]}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[open,setOpen]=useState(false),[consent,setConsent]=useState<Mission|null>(null),[accepted,setAccepted]=useState(false),[cancel,setCancel]=useState<Mission|null>(null),[now,setNow]=useState(Date.now());
 const [draft,setDraft]=useState({title:'이번 주 3일 함께 운동',starts:localDate(),ends:addDays(localDate(),6),target:3,promise:'',coffeePrice:0});
 const load=useCallback(async(signal?:AbortSignal)=>{try{const r=await fetch(`/api/missions?crew=${encodeURIComponent(crew.id)}`,{cache:'no-store',signal});const value=await r.json() as typeof data&{error?:string};if(!r.ok)throw Error(value.error);if(!signal?.aborted){setData(value);setError('');}}catch(e){if(!signal?.aborted)setError((e as Error).message);}},[crew.id]);
 useEffect(()=>{const c=new AbortController();void load(c.signal);const refresh=()=>{setNow(Date.now());if(document.visibilityState==='visible')void load(c.signal);};const timer=setInterval(refresh,15000);window.addEventListener('focus',refresh);return()=>{c.abort();clearInterval(timer);window.removeEventListener('focus',refresh);};},[load,crew.revision]);
 async function act(input:Record<string,unknown>){setBusy(true);setError('');try{const r=await fetch('/api/missions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...input,crewId:crew.id})});const value=await r.json() as {error?:string};if(!r.ok)throw Error(value.error);await load();return true;}catch(e){setError((e as Error).message);return false;}finally{setBusy(false);}}
 const sessions=crew.state.sessions.filter(s=>!s.cancelled&&now>=sessionStart(s)-30*60000&&now<=sessionStart(s)+12*3600000);
 const name=(id:string)=>crew.members.find(m=>m.userId===id)?.name||'이전 크루원';
 return <section className="panel crew-activity"><div className="section-line"><div><h2>출석 & 크루 미션</h2><p className="muted">약속을 지킨 하루를, 함께 쌓아요.</p></div><button className="secondary" onClick={()=>{setAccepted(false);setOpen(true);}}><Plus size={15}/>미션 만들기</button></div>{error&&<p role="alert" className="form-error">{error}</p>}
 <div className="checkin-section"><h3>오늘의 출석</h3><p className="muted">일정 시작 30분 전~시작 후 12시간에 체크하고, 같이 운동한 친구가 확인해주세요.</p>{sessions.length?sessions.map(s=>{const own=data.checkins.find(c=>c.session_id===s.id&&c.user_id===userId),pending=data.checkins.filter(c=>c.session_id===s.id&&c.user_id!==userId&&!c.confirmed_by);return <div className="checkin-card" key={s.id}><div className="section-line"><div><strong>{s.time} · {s.title}</strong><p className="muted">{s.date} · {own?.confirmed_by?'친구 확인 완료':own?'친구 확인 대기':'출석 전'}</p></div><button className={own?'secondary':'primary'} disabled={busy||!!own||!s.participants.includes(userId)} onClick={()=>void act({action:'checkin',sessionId:s.id})}><Check size={15}/>{own?'출석 체크됨':s.participants.includes(userId)?'출석 체크':'일정 참여 후 체크'}</button></div>{pending.map(c=><div className="checkin-friend" key={c.user_id}><span>{name(c.user_id)} · 확인 대기</span><button className="text-button" disabled={busy} onClick={()=>void act({action:'confirm',sessionId:s.id,userId:c.user_id})}>함께 운동 확인</button></div>)}</div>;}):<p className="activity-empty">지금 출석할 수 있는 일정이 없어요. 운동 일정에 참여하면 여기에 표시돼요.</p>}</div>
 <div className="mission-grid">{data.missions.map(m=>{const own=m.progress.find(p=>p.userId===userId),joined=own&&!own.withdrawn;return <article className="mission-card" key={m.id}><div className="section-line"><span className="status-chip">{m.cancelled?'취소됨':m.finished?'결과':'진행 중'}</span><Flag size={16}/></div><h3>{m.title}</h3><p className="muted">{m.starts} ~ {m.ends} · 출석 {m.target}일</p><p className="mission-promise">{m.promise||'보상·벌칙 없이 서로 응원하는 미션'}</p><div className="mission-progress">{m.progress.map(p=><div key={p.userId}><div><span>{name(p.userId)}</span><strong>{p.withdrawn?'참여 취소':`${p.days} / ${m.target}일${p.days>=m.target?' · 달성':m.finished?' · 미달성':''}`}</strong></div><progress max={m.target} value={p.withdrawn?0:Math.min(p.days,m.target)}/></div>)}</div>{!m.cancelled&&!m.finished&&<div className="button-row">{joined?<button className="secondary" disabled={busy} onClick={()=>void act({action:'withdraw',missionId:m.id})}>미션 참여 취소</button>:<button className="primary" disabled={busy||localDate()>m.ends} onClick={()=>{setAccepted(false);setConsent(m);}}>조건 보고 참여</button>}{(m.creator===userId||crew.owner===userId)&&<button className="text-button" onClick={()=>setCancel(m)}>미션 종료·취소</button>}</div>}<CoffeeResult mission={m} userId={userId} canFinalize={m.creator===userId||crew.owner===userId} busy={busy} name={name} act={act}/>{m.finished&&m.promise&&!m.cancelled&&!m.coffee_price&&<p className="muted">결과를 확인하고 친구끼리 약속을 정산해주세요. 앱에서 결제하지 않아요.</p>}</article>;})}</div>{!data.missions.length&&<p className="activity-empty">첫 미션을 만들어 친구들을 초대해보세요.</p>}
 <p className="muted activity-rules">친구가 확인한 출석만 하루 1회 인정해요. 참여 동의 이후의 출석부터 집계하며, 취소·변경된 일정은 다시 확인해야 해요. 종료 다음 날 정오 이후 결과를 확인하세요.</p>
 <Dialog open={open} onOpenChange={v=>!busy&&setOpen(v)}><DialogContent className="app-dialog mission-dialog"><DialogTitle>크루 미션 만들기</DialogTitle><DialogDescription>목표와 약속은 참여 전에 정해요. 등록 후 조건은 바꿀 수 없으며, 취소 후 새로 만들 수 있어요.</DialogDescription><form className="form-stack" onSubmit={async e=>{e.preventDefault();if(await act({action:'create',...draft,accepted}))setOpen(false);}}><fieldset disabled={busy}><label className="field">미션 이름<input required maxLength={80} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><div className="two-fields"><label className="field">시작일<input required type="date" min={localDate()} value={draft.starts} onChange={e=>setDraft({...draft,starts:e.target.value})}/></label><label className="field">종료일<input required type="date" min={draft.starts} max={addDays(draft.starts,89)} value={draft.ends} onChange={e=>setDraft({...draft,ends:e.target.value})}/></label></div><label className="field">목표 출석 일수<input type="number" required min={1} max={90} value={draft.target} onChange={e=>setDraft({...draft,target:Number(e.target.value)})}/></label><label className="mission-consent"><input type="checkbox" checked={draft.coffeePrice>0} onChange={e=>setDraft({...draft,coffeePrice:e.target.checked?5000:0})}/>실패자가 성공자 커피 사기</label>{draft.coffeePrice>0&&<><label className="field">아메리카노 한 잔 기준 금액 (원)<input type="number" required min={100} max={20000} step={100} value={draft.coffeePrice} onChange={e=>setDraft({...draft,coffeePrice:Number(e.target.value)})}/></label><p className="muted">성공자에게 한 잔씩, 실패자들이 총액을 균등 부담합니다. 실패자 한 명이 구매를 맡고 나머지가 부담액을 전달합니다. 전원 성공·전원 실패면 정산하지 않습니다.</p></>}<label className="field">추가 약속 (선택)<input maxLength={200} value={draft.promise} onChange={e=>setDraft({...draft,promise:e.target.value})} placeholder="예: 미달성자는 참여자에게 아메리카노 한 잔"/></label><label className="mission-consent"><input type="checkbox" required checked={accepted} onChange={e=>setAccepted(e.target.checked)}/>목표·출석 기준·약속에 동의하고 참여합니다. 금전 자동이체나 앱 결제는 없습니다.</label></fieldset>{error&&<p className="form-error">{error}</p>}<button className="primary" disabled={busy||!accepted}>미션 만들고 참여</button></form></DialogContent></Dialog>
 <Dialog open={!!consent} onOpenChange={v=>!v&&!busy&&setConsent(null)}><DialogContent className="app-dialog"><DialogTitle>{consent?.title}</DialogTitle><DialogDescription>{consent?.starts} ~ {consent?.ends} · 친구 확인 출석 {consent?.target}일</DialogDescription><p>{consent?.promise||'별도 추가 약속 없음'}</p>{!!consent?.coffee_price&&<p>아메리카노 잔당 {consent.coffee_price.toLocaleString()}원. 성공자 1명당 1잔을 실패자가 균등 부담합니다. 실패자 한 명이 구매하고 나머지가 부담액을 전달해요. 전원 성공·전원 실패면 정산이 없습니다.</p>}<p className="muted">동의한 시점 이후 출석만 인정합니다. 앱은 돈을 보관하거나 자동이체하지 않으며, 약속은 친구끼리 처리합니다.</p><label className="mission-consent"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/>위 조건에 동의합니다.</label>{error&&<p className="form-error">{error}</p>}<button className="primary" disabled={busy||!accepted} onClick={async()=>{if(consent&&await act({action:'join',missionId:consent.id,accepted}))setConsent(null);}}>동의하고 참여</button></DialogContent></Dialog>
 <Dialog open={!!cancel} onOpenChange={v=>!v&&!busy&&setCancel(null)}><DialogContent className="app-dialog"><DialogTitle>미션을 취소할까요?</DialogTitle><DialogDescription>전체 참여자의 미션이 취소됩니다. 출석 기록은 유지됩니다.</DialogDescription><button className="danger" disabled={busy} onClick={async()=>{if(cancel&&await act({action:'cancel',missionId:cancel.id}))setCancel(null);}}>미션 취소</button></DialogContent></Dialog>
 </section>;
}
