'use client';
import './crew-tools.css';
import { useEffect, useState } from 'react';
import { Plus, Vote, CalendarCheck, Settings, Bell, RefreshCw, LogOut, X } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { AlertDialog, AlertDialogContent, AlertDialogTitle, AlertDialogDescription, AlertDialogCancel } from '@/components/ui/alert-dialog';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Checkbox } from '@/components/ui/checkbox';
import { Switch } from '@/components/ui/switch';
import { toast } from 'sonner';
import { addDays, localDate, type Crew, type Snapshot } from '@/lib/gym-model';
import { WEEKDAYS } from '@/lib/planning';
type Mutate=(payload:Record<string,unknown>,message:string)=>Promise<boolean>;
type Props={crew:Crew;userId:string;mutate:Mutate;busy:boolean};
function RoutineChoice({crew,value,onChange,label}:{crew:Crew;value:string;onChange:(v:string)=>void;label:string}){return <Select value={value||'none'} onValueChange={v=>onChange(v==='none'?'':v)}><SelectTrigger aria-label={label} className="choice"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">자유 운동 / 휴식</SelectItem>{crew.state.routines.map(r=><SelectItem value={r.id} key={r.id}>{r.name}</SelectItem>)}</SelectContent></Select>;}

export function WeekPlan({crew,mutate,busy}:Props){
 const [open,setOpen]=useState(false),[plan,setPlan]=useState<Record<string,string>>({}),[revision,setRevision]=useState(0);
 return <section className="panel planning-panel"><div className="section-line"><div><h2>요일별 공통 루틴</h2><p className="muted">새 일정을 만들 때 요일에 맞춰 자동으로 선택해요.</p></div><button className="secondary" onClick={()=>{setPlan({...crew.state.weekPlan});setRevision(crew.revision);setOpen(true);}}>요일 배정</button></div><div className="plan-week">{[1,2,3,4,5,6,0].map(d=><div key={d}><strong>{WEEKDAYS[d]}</strong><span>{crew.state.routines.find(r=>r.id===crew.state.weekPlan?.[d])?.name||'자유 / 휴식'}</span></div>)}</div><Dialog open={open} onOpenChange={v=>!busy&&setOpen(v)}><DialogContent className="app-dialog"><DialogTitle>요일별 루틴 배정</DialogTitle><DialogDescription>이미 만들어진 일정은 바뀌지 않아요. 새 일정부터 적용됩니다.</DialogDescription><form className="form-stack" onSubmit={async e=>{e.preventDefault();if(await mutate({action:'saveWeekPlan',plan,revision},'요일별 루틴을 저장했어요.'))setOpen(false);}}><fieldset disabled={busy}>{[1,2,3,4,5,6,0].map(d=><div className="plan-edit" key={d}><label>{WEEKDAYS[d]}요일</label><RoutineChoice crew={crew} label={`${WEEKDAYS[d]}요일 루틴`} value={plan[d]||''} onChange={v=>setPlan({...plan,[d]:v})}/></div>)}</fieldset><button className="primary" disabled={busy}>배정 저장</button></form></DialogContent></Dialog></section>;
}

export function PollManager({crew,userId,mutate,busy}:Props){
 const [open,setOpen]=useState(false),[title,setTitle]=useState(''),[routineId,setRoutineId]=useState(''),[capacity,setCapacity]=useState(''),[closes,setCloses]=useState('');
 const [options,setOptions]=useState<{date:string;time:string}[]>([]),[votes,setVotes]=useState<Record<string,string[]>>({});
 const [confirmation,setConfirmation]=useState<{pollId:string;optionId?:string}|null>(null);
 function start(){setTitle('');setRoutineId('');setCapacity('');setCloses(new Date(Date.now()+10*3600000).toISOString().slice(0,16));setOptions([1,2].map(n=>({date:addDays(localDate(),n),time:'19:00'})));setOpen(true);}
 const polls=[...(crew.state.polls??[])].reverse();
 return <section className="planning-section"><div className="section-line lower-heading"><div><h2>언제 같이 운동할까요?</h2><p className="muted">가능한 시간을 모두 체크해요. 확정 후 일정에서 참여를 신청하세요.</p></div><button className="secondary" onClick={start}><Vote size={16}/> 시간 투표 만들기</button></div>{!polls.length?<p className="muted panel">진행 중인 시간 투표가 없어요.</p>:<div className="poll-grid">{polls.map(poll=>{const selected=votes[poll.id]??poll.options.filter(o=>o.votes.includes(userId)).map(o=>o.id);const isOwner=poll.creator===userId||crew.owner===userId;const live=poll.status==='open';const canVote=live&&Date.now()<poll.closesAt;return <article className="panel poll-card" key={poll.id}><div className="section-line"><h3>{poll.title}</h3><span className="status-chip">{poll.status==='confirmed'?'일정 확정':poll.status==='closed'?'종료':canVote?'투표 중':'투표 마감'}</span></div><p className="muted">마감 {new Date(poll.closesAt).toLocaleString('ko-KR',{timeZone:'Asia/Seoul',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})} · 서울</p><div className="poll-options">{poll.options.map(option=><div className="poll-option" key={option.id}><label><Checkbox checked={selected.includes(option.id)} disabled={!canVote||busy} onCheckedChange={checked=>setVotes({...votes,[poll.id]:checked?[...selected,option.id]:selected.filter(id=>id!==option.id)})}/><span>{option.date} <strong>{option.time}</strong><small>{option.votes.length}명 가능</small></span></label>{isOwner&&live&&<button className="text-button" disabled={busy} onClick={()=>setConfirmation({pollId:poll.id,optionId:option.id})}>이 시간 확정</button>}</div>)}</div><div className="button-row">{canVote&&<button className="primary" disabled={busy} onClick={async()=>{if(await mutate({action:'votePoll',pollId:poll.id,optionIds:selected},'가능한 시간을 저장했어요.'))setVotes(previous=>{const next={...previous};delete next[poll.id];return next;});}}>내 가능 시간 저장</button>}{isOwner&&live&&<button className="text-button" disabled={busy} onClick={()=>setConfirmation({pollId:poll.id})}>투표 종료</button>}{poll.status==='confirmed'&&<span className="muted"><CalendarCheck size={15}/> 운동 일정에서 참여할 수 있어요.</span>}</div></article>;})}</div>}
 <Dialog open={open} onOpenChange={v=>!busy&&setOpen(v)}><DialogContent className="app-dialog"><DialogTitle>가능한 시간 투표</DialogTitle><DialogDescription>후보는 2~12개, 투표 마감은 모든 후보 시간보다 앞서야 해요.</DialogDescription><form className="form-stack" onSubmit={async e=>{e.preventDefault();if(await mutate({action:'createPoll',title,routineId,capacity:capacity?Number(capacity):null,closesAt:new Date(`${closes}:00+09:00`).getTime(),options},'시간 투표를 만들었어요.'))setOpen(false);}}><fieldset disabled={busy}><label className="field">투표 이름<input required maxLength={60} value={title} onChange={e=>setTitle(e.target.value)} placeholder="이번 주 하체 언제 할까?"/></label><label className="field">투표 마감 (서울)<input type="datetime-local" required value={closes} onInput={e=>setCloses(e.currentTarget.value)} onChange={e=>setCloses(e.target.value)}/></label><div className="field"><label>함께할 루틴</label><RoutineChoice crew={crew} label="투표 루틴" value={routineId} onChange={setRoutineId}/></div><label className="field">확정 일정 정원<input type="number" min={1} max={100} value={capacity} onChange={e=>setCapacity(e.target.value)} placeholder="비워두면 제한 없음"/></label>{options.map((option,i)=><div className="poll-edit-option" key={i}><input aria-label={`후보 ${i+1} 날짜`} type="date" required value={option.date} onInput={e=>setOptions(options.map((o,j)=>i===j?{...o,date:e.currentTarget.value}:o))} onChange={()=>{}}/><input aria-label={`후보 ${i+1} 시간`} type="time" required value={option.time} onInput={e=>{const value=e.currentTarget.value;setOptions(options.map((o,j)=>i===j?{...o,time:value}:o));}} onChange={()=>{}}/><button type="button" className="icon-button" aria-label={`후보 ${i+1} 삭제`} disabled={options.length<=2} onClick={()=>setOptions(options.filter((_,j)=>j!==i))}><X size={15}/></button></div>)}<button type="button" className="secondary" disabled={options.length>=12} onClick={()=>setOptions([...options,{date:addDays(localDate(),options.length+1),time:'19:00'}])}><Plus size={16}/>후보 시간 추가</button></fieldset><button className="primary" disabled={busy}>투표 만들기</button></form></DialogContent></Dialog>
 <AlertDialog open={!!confirmation} onOpenChange={v=>!v&&!busy&&setConfirmation(null)}><AlertDialogContent className="app-dialog"><AlertDialogTitle>{confirmation?.optionId?'이 시간으로 운동 일정을 만들까요?':'시간 투표를 종료할까요?'}</AlertDialogTitle><AlertDialogDescription>{confirmation?.optionId?'투표는 종료되고 운동 일정이 생성됩니다. 가능한 시간을 고른 친구도 별도로 참여 신청을 해야 합니다.':'더 이상 투표할 수 없으며, 운동 일정은 생성되지 않습니다.'}</AlertDialogDescription><div className="button-row"><AlertDialogCancel disabled={busy}>돌아가기</AlertDialogCancel><button className="primary" disabled={busy} onClick={async()=>{if(confirmation&&await mutate({action:confirmation.optionId?'confirmPoll':'closePoll',...confirmation},confirmation.optionId?'운동 일정을 확정했어요.':'투표를 종료했어요.'))setConfirmation(null);}}>확인</button></div></AlertDialogContent></AlertDialog>
 </section>;
}

export function CrewManager({crew,userId,mutate,busy}:Props){
 const [name,setName]=useState(crew.name),[target,setTarget]=useState(''),[confirm,setConfirm]=useState<'rotate'|'transfer'|'leave'|null>(null);
 useEffect(()=>{setName(crew.name);setTarget('');setConfirm(null);},[crew.id,crew.name]);
 const owner=crew.owner===userId;
 return <section className="panel planning-panel"><div className="section-line"><h2><Settings size={19}/> 크루 관리</h2><span className="muted">{owner?'크루장':'크루원'}</span></div>{owner&&<><form className="manage-row" onSubmit={async e=>{e.preventDefault();await mutate({action:'renameCrew',name},'크루 이름을 변경했어요.');}}><label className="field">크루 이름<input required maxLength={60} value={name} onChange={e=>setName(e.target.value)}/></label><button className="secondary" disabled={busy||name===crew.name}>이름 변경</button></form><div className="manage-row"><div><h3>초대 링크 재발급</h3><p className="muted">이전 링크는 더 이상 가입에 사용할 수 없어요.</p></div><button className="secondary" disabled={busy} onClick={()=>setConfirm('rotate')}><RefreshCw size={15}/> 재발급</button></div><div className="manage-row"><div className="field"><label>크루장 위임</label><Select value={target} onValueChange={setTarget}><SelectTrigger className="choice" aria-label="새 크루장"><SelectValue placeholder="크루원을 선택하세요"/></SelectTrigger><SelectContent>{crew.members.filter(m=>m.userId!==userId).map(m=><SelectItem key={m.userId} value={m.userId}>{m.name}</SelectItem>)}</SelectContent></Select></div><button className="secondary" disabled={busy||!target} onClick={()=>setConfirm('transfer')}>크루장 위임</button></div></>}<div className="manage-row"><div><h3>크루 탈퇴</h3><p className="muted">{owner&&crew.members.length>1?'다른 멤버에게 크루장을 위임한 뒤 탈퇴할 수 있어요.':crew.members.length===1?'마지막 멤버가 탈퇴하면 크루가 보관되고 초대 링크가 종료돼요.':'참여 일정과 투표에서 빠지고 크루 알림을 받지 않아요.'}</p></div><button className="danger" disabled={busy||(owner&&crew.members.length>1)} onClick={()=>setConfirm('leave')}><LogOut size={15}/> 탈퇴</button></div><AlertDialog open={!!confirm} onOpenChange={v=>!v&&!busy&&setConfirm(null)}><AlertDialogContent className="app-dialog"><AlertDialogTitle>{confirm==='rotate'?'초대 링크를 재발급할까요?':confirm==='transfer'?'크루장을 위임할까요?':'크루에서 탈퇴할까요?'}</AlertDialogTitle><AlertDialogDescription>{confirm==='rotate'?'기존 링크로는 새 멤버가 가입할 수 없게 됩니다.':confirm==='transfer'?'선택한 멤버에게 크루 관리 권한이 넘어갑니다.': '크루 일정과 투표에서 빠집니다. 기존 개인 루틴 데이터는 보관되지만 탈퇴 중에는 접근할 수 없습니다.'}</AlertDialogDescription><div className="button-row"><AlertDialogCancel disabled={busy}>돌아가기</AlertDialogCancel><button className="primary" disabled={busy} onClick={async()=>{if(await mutate({action:confirm==='rotate'?'rotateInvite':confirm==='transfer'?'transferOwner':'leaveCrew',userId:target},confirm==='leave'?'크루에서 탈퇴했어요.':'크루 설정을 변경했어요.'))setConfirm(null);}}>확인</button></div></AlertDialogContent></AlertDialog></section>;
}

export function NotificationCenter({snapshot,mutate,busy,onNavigate}:{snapshot:Snapshot;mutate:Mutate;busy:boolean;onNavigate:(crewId:string,sessionId:string)=>void}){
 const [open,setOpen]=useState(false),[working,setWorking]=useState(false),[supported,setSupported]=useState(false),[device,setDevice]=useState(false);
 const items=snapshot.notifications?.items??[],pref=snapshot.notifications?.settings??{enabled:1,push_enabled:0,reminder_minutes:60};
 useEffect(()=>{setSupported('serviceWorker' in navigator&&'PushManager' in window&&'Notification' in window);if('serviceWorker' in navigator)void navigator.serviceWorker.getRegistration('/').then(r=>r?.pushManager.getSubscription()).then(s=>setDevice(!!s));},[]);
 async function enableDevice(){const permission=Notification.requestPermission();setWorking(true);try{
  if(await permission!=='granted')throw new Error('알림이 허용되지 않았어요. 브라우저의 사이트 설정에서 알림을 허용해주세요.');
  const response=await fetch('/api/notifications/push');const config=await response.json() as {publicKey?:string;error?:string};if(!config.publicKey)throw new Error(config.error||'푸시 연결을 준비 중이에요. 웹 안 알림은 사용할 수 있어요.');
  const registration=await navigator.serviceWorker.register('/sw.js',{scope:'/'});await navigator.serviceWorker.ready;
  const base64=config.publicKey.replace(/-/g,'+').replace(/_/g,'/');const raw=atob(base64.padEnd(Math.ceil(base64.length/4)*4,'='));const key=Uint8Array.from(raw,c=>c.charCodeAt(0));
  const subscription=await registration.pushManager.getSubscription()??await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:key});
  const saved=await fetch('/api/notifications/push',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(subscription)});
  if(!saved.ok)throw new Error('기기 알림 등록에 실패했어요. 다시 시도해주세요.');
  setDevice(true);await mutate({action:'notificationSettings',enabled:true,pushEnabled:true,reminderMinutes:pref.reminder_minutes},'이 기기로 운동 알림을 받아요.');
 }catch(error){toast.error((error as Error).message);}finally{setWorking(false);}}
 async function disableDevice(){setWorking(true);try{const registration=await navigator.serviceWorker.getRegistration('/');const subscription=await registration?.pushManager.getSubscription();if(subscription){const response=await fetch('/api/notifications/push',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({endpoint:subscription.endpoint})});if(!response.ok)throw new Error('기기 알림 해제에 실패했어요.');await subscription.unsubscribe();}setDevice(false);toast.success('이 기기의 푸시 알림을 껐어요.');}catch(error){toast.error((error as Error).message);}finally{setWorking(false);}}
 return <><button className="icon-button notification-bell" aria-label={`알림 ${items.filter(n=>!n.readAt).length}개 읽지 않음`} onClick={()=>setOpen(true)}><Bell size={19}/>{items.some(n=>!n.readAt)&&<span/>}</button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="app-dialog notifications-dialog"><DialogTitle>운동 알림</DialogTitle><DialogDescription>참여한 일정의 시작 전과 시간 변경·취소 소식을 확인해요.</DialogDescription><div className="notification-settings"><label className="switch-row">일정 알림 받기<Switch checked={!!pref.enabled} disabled={busy} onCheckedChange={enabled=>void mutate({action:'notificationSettings',enabled,pushEnabled:!!pref.push_enabled,reminderMinutes:pref.reminder_minutes},'알림 설정을 저장했어요.')}/></label><div className="field"><label>운동 전 알림</label><Select value={String(pref.reminder_minutes)} onValueChange={v=>void mutate({action:'notificationSettings',enabled:!!pref.enabled,pushEnabled:!!pref.push_enabled,reminderMinutes:Number(v)},'알림 시간을 변경했어요.')}><SelectTrigger className="choice" aria-label="운동 전 알림 시간"><SelectValue/></SelectTrigger><SelectContent>{[10,30,60,1440].map(v=><SelectItem value={String(v)} key={v}>{v===1440?'하루 전':`${v}분 전`}</SelectItem>)}</SelectContent></Select></div><button className="secondary" disabled={!supported||working||busy} onClick={()=>void(device?disableDevice():enableDevice())}>{working?'연결 중…':device?'이 기기 푸시 끄기':'이 기기에 푸시 알림 켜기'}</button>{!supported&&<p className="muted">이 브라우저에서는 푸시 알림을 지원하지 않아요.</p>}<p className="muted">아이폰은 홈 화면에 추가한 웹 앱에서 알림을 허용해주세요. 기기 설정과 절전 상태에 따라 도착이 늦어질 수 있어요.</p></div><div className="section-line"><h3>최근 알림</h3><button className="text-button" disabled={busy||!items.some(n=>!n.readAt)} onClick={()=>void mutate({action:'readNotifications',ids:items.filter(n=>!n.readAt).map(n=>n.id)},'모두 읽음으로 표시했어요.')}>모두 읽음</button></div><div className="inbox-list">{items.length?items.map(n=><button className={`inbox-item ${n.readAt?'':'unread'}`} key={n.id} onClick={async()=>{await mutate({action:'readNotifications',ids:[n.id]},'알림을 확인했어요.');setOpen(false);onNavigate(n.crewId,n.sessionId);}}><strong>{n.title}</strong><span>{n.body}</span><small>{new Date(Number(n.dueAt)).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})}</small></button>):<p className="muted">아직 도착한 알림이 없어요.</p>}</div></DialogContent></Dialog></>;
}
