'use client';
import {useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import type {MusicRecommendation} from '@/lib/music-model';
import {youtubeSource} from '@/lib/music-model';
import {ExternalLink,ListMusic} from 'lucide-react';
import './music-transfer.css';
const isMix=(item:MusicRecommendation)=>!!youtubeSource(item.youtube_url)?.list||/playlist|\bmix\b|플리|믹스|모음|운동음악|운동노래|운동할때|workout|bodybuilding|chris bumstead|cbum/i.test(item.title.normalize('NFKC'));
export function MusicTransfer({items,userId,single=false}:{items:MusicRecommendation[];userId?:string;single?:boolean}){
 const [open,setOpen]=useState(false),[title,setTitle]=useState('SPOT 운동 음악'),[selected,setSelected]=useState<Record<string,boolean>>({}),[names,setNames]=useState<Record<string,{title:string;artist:string}>>({}),[manual,setManual]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[url,setUrl]=useState('');
 const eligible=items.filter(i=>!isMix(i));
 function start(){setUrl('');setError('');setManual('');setSelected(Object.fromEntries(eligible.map(i=>[i.id,true])));setNames(Object.fromEntries(eligible.map(i=>[i.id,{title:i.title,artist:i.artist}])));setOpen(true);}
 const tracks=[...eligible.filter(i=>selected[i.id]).map(i=>names[i.id]??{title:i.title,artist:i.artist}),...manual.split('\n').filter(x=>x.trim()).map(x=>{const [title,...rest]=x.split('|');return {title:title.trim(),artist:rest.join('|').trim()};})];
 async function transfer(){setBusy(true);setError('');setUrl('');try{const r=await fetch('/api/music/transfer',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title,tracks})});const data=await r.json() as {url?:string;error?:string};if(!r.ok||!data.url)throw Error(data.error||'전송하지 못했어요.');setUrl(data.url);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <><button className="secondary" onClick={start}><ListMusic size={16}/>{single?'내 음악 앱에 저장':'추천곡을 내 앱에 저장'}</button><Dialog open={open} onOpenChange={v=>!busy&&setOpen(v)}><DialogContent className="app-dialog transfer-dialog"><DialogTitle>내 음악 앱에 플레이리스트 저장</DialogTitle><DialogDescription>곡을 확인한 뒤 Soundiiz에서 음악 앱 계정을 연결해 저장합니다. Spotify·Apple Music·YouTube Music 등 지원 앱을 다음 화면에서 선택하세요.</DialogDescription>{!userId?<a className="primary" href="/login">로그인하고 계속</a>:url?<><p className="transfer-success">곡 목록을 전달했어요. 아직 음악 앱에 저장된 것은 아닙니다.</p><a className="primary" href={url} target="_blank" rel="noopener noreferrer">음악 앱 연결하고 저장하기<ExternalLink size={16}/></a><p className="muted">전송 화면에서 매칭된 곡을 확인하고 저장을 완료해주세요. 링크는 24시간 동안 유효합니다.</p><button className="text-button" onClick={()=>setUrl('')}>곡 목록 다시 수정</button></>:<><label className="field">새 플레이리스트 이름<input maxLength={120} value={title} onChange={e=>setTitle(e.target.value)}/></label>{items.length!==eligible.length&&<p className="transfer-notice">믹스·플레이리스트 영상 {items.length-eligible.length}개는 자동 곡 매칭에서 제외했어요. 영상 안 원곡을 옮기려면 아래에 곡 제목과 아티스트를 직접 입력해주세요.</p>}<div className="transfer-tracks">{eligible.map(i=><div className="transfer-track" key={i.id}><input type="checkbox" aria-label={`${i.title} 선택`} checked={!!selected[i.id]} onChange={e=>setSelected({...selected,[i.id]:e.target.checked})}/><label className="field">곡 제목<input maxLength={200} value={names[i.id]?.title??i.title} onChange={e=>setNames({...names,[i.id]:{...names[i.id],title:e.target.value}})}/></label><label className="field">아티스트<input maxLength={160} value={names[i.id]?.artist??i.artist} onChange={e=>setNames({...names,[i.id]:{...names[i.id],artist:e.target.value}})}/></label></div>)}</div><label className="field">원곡 목록 직접 추가 (선택)<textarea rows={4} value={manual} onChange={e=>setManual(e.target.value)} placeholder={'곡 제목 | 아티스트\n한 줄에 한 곡씩 입력'}/></label><p className="muted">선택한 제목·아티스트만 Soundiiz에 전달합니다. 계정 연결과 최종 저장은 전송 화면에서 직접 진행합니다. 곡의 국가·카탈로그에 따라 일부가 매칭되지 않을 수 있어요.</p><p className="muted">멜론·지니·FLO·VIBE·벅스는 이 전송 서비스에서 현재 지원하지 않아요. 무료 전송은 한 번에 한 플레이리스트, 최대 200곡이며 유료 결제는 자동 진행하지 않습니다.</p>{error&&<p className="form-error" role="alert">{error}</p>}<button className="primary" disabled={busy||tracks.length===0||tracks.length>200||!title.trim()} onClick={()=>void transfer()}>{busy?'전송 준비 중…':`${tracks.length}곡 전송 화면 열기`}</button></> }</DialogContent></Dialog></>;
}
