'use client';
import {useCallback,useEffect,useState} from 'react';
import {Music2,Plus,Play,ExternalLink,Pencil,X,Headphones} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {musicServices,youtubeSource,type MusicRecommendation} from '@/lib/music-model';
import './music-recommendations.css';
const empty:MusicRecommendation={id:'',title:'',artist:'',description:'',youtube_url:'',links:[],revision:0};

export function MusicRecommendations({userId}:{userId?:string}){
 const [items,setItems]=useState<MusicRecommendation[]>([]),[admin,setAdmin]=useState(false),[ready,setReady]=useState(false),[error,setError]=useState('');
 const [draft,setDraft]=useState<MusicRecommendation|null>(null),[active,setActive]=useState<MusicRecommendation|null>(null),[busy,setBusy]=useState(false),[formError,setFormError]=useState(''),[remove,setRemove]=useState<MusicRecommendation|null>(null);
 const load=useCallback(async(signal?:AbortSignal)=>{try{const r=await fetch('/api/music',{signal,cache:'no-store'});const data=await r.json() as {items:MusicRecommendation[];admin:boolean;error?:string};if(!r.ok)throw Error(data.error);if(!signal?.aborted){setItems(data.items);setAdmin(data.admin);setError('');setReady(true);}}catch(e){if(!signal?.aborted){setError((e as Error).message);setReady(true);}}},[]);
 useEffect(()=>{const c=new AbortController();setAdmin(false);void load(c.signal);const focus=()=>void load(c.signal);window.addEventListener('focus',focus);return()=>{c.abort();window.removeEventListener('focus',focus);};},[load,userId]);
 async function post(body:unknown){const r=await fetch('/api/music',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json() as {title?:string;artist?:string;note?:string;error?:string};if(!r.ok)throw Error(data.error||'저장하지 못했어요.');return data;}
 async function save(){if(!draft)return;setBusy(true);setFormError('');try{await post({action:'save',item:draft});setDraft(null);await load();}catch(e){setFormError((e as Error).message);}finally{setBusy(false);}}
 async function preview(){if(!draft)return;setBusy(true);setFormError('');try{const data=await post({action:'preview',url:draft.youtube_url});setDraft({...draft,title:draft.title||data.title||'',artist:draft.artist||data.artist||''});if(data.note)setFormError(data.note);}catch(e){setFormError((e as Error).message);}finally{setBusy(false);}}
 function edit(item:MusicRecommendation){setFormError('');setDraft(structuredClone(item));}
 const source=active?youtubeSource(active.youtube_url):null;
 return <section className="music-section" aria-label="헬스장 음악 추천">
  <div className="section-line"><div><p className="eyebrow">SPOT SOUND</p><h2>헬스장 음악 추천</h2><p className="muted">오늘의 운동에, 좋은 비트 하나.</p></div>{admin&&<button className="secondary" onClick={()=>edit(empty)}><Plus size={16}/>음악 추천 추가</button>}</div>
  {error?<div className="music-empty" role="status">{error}<button className="text-button" onClick={()=>void load()}>다시 불러오기</button></div>:!ready?<p className="music-empty">추천 음악을 불러오는 중…</p>:!items.length?<div className="music-empty"><Headphones size={25}/><strong>다음 운동의 배경음악을 준비 중이에요.</strong><span>{admin?'유튜브 노래나 플레이리스트를 하나씩 추천해주세요.':'관리자가 추천한 음악이 여기에 모여요.'}</span></div>:<div className="music-grid">{items.map(item=>{const s=youtubeSource(item.youtube_url);return <article className="music-card" key={item.id}><button className="music-cover" aria-label={`${item.title} 미리 듣기`} onClick={()=>setActive(item)}>{s?.video&&<img src={`https://i.ytimg.com/vi/${s.video}/hqdefault.jpg`} alt="" loading="lazy"/>}<div className="music-cover-content"><Music2 size={25}/><span>{s?.kind??'MUSIC'}</span><strong>{item.title}</strong><small>{item.artist||'SPOT SELECTED'}</small></div><span className="music-play"><Play size={20} fill="currentColor"/></span></button><div className="music-card-bottom"><p>{item.description||'운동할 때 함께 듣기 좋은 음악'}</p><div className="music-actions"><button className="text-button" onClick={()=>setActive(item)}>듣기 · 음악 앱 선택 <ExternalLink size={14}/></button>{admin&&<button className="icon-button" aria-label={`${item.title} 추천 수정`} onClick={()=>edit(item)}><Pencil size={16}/></button>}</div></div></article>;})}</div>}
  <Dialog open={!!active} onOpenChange={v=>!v&&setActive(null)}><DialogContent className="app-dialog music-player-dialog"><DialogTitle>{active?.title}</DialogTitle><DialogDescription>{active?.artist||'SPOT 음악 추천'} · 유튜브 공식 플레이어</DialogDescription>{source&&<iframe key={source.embed} className="music-player" src={source.embed} title={`${active?.title} 유튜브 플레이어`} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen referrerPolicy="strict-origin-when-cross-origin"/>}<p className="muted">재생 버튼을 눌러 들어보세요. 영상의 외부 재생이 제한된 경우 음악 앱에서 열어주세요.</p><h3>내 음악 앱에서 듣기</h3><div className="music-app-links">{source&&<a className="primary" href={source.musicUrl} target="_blank" rel="noopener noreferrer">YouTube Music <ExternalLink size={15}/></a>}{active?.links.map(link=><a key={link.service} className="secondary" href={link.url} target="_blank" rel="noopener noreferrer">{link.service}<ExternalLink size={15}/></a>)}</div><p className="muted">연결된 곡·플레이리스트 링크입니다. 설치 상태에 따라 앱 또는 웹으로 열려요. 앱별 링크는 관리자가 추가하며 자동 플레이리스트 변환은 제공하지 않습니다.</p></DialogContent></Dialog>
  <Dialog open={!!draft} onOpenChange={v=>!v&&!busy&&setDraft(null)}><DialogContent className="app-dialog music-editor"><DialogTitle>{draft?.id?'음악 추천 수정':'음악 추천 추가'}</DialogTitle><DialogDescription>모든 크루에 보이는 관리자 추천입니다. 공개된 유튜브 노래나 플레이리스트를 넣어주세요.</DialogDescription>{draft&&<form className="form-stack" onSubmit={e=>{e.preventDefault();void save();}}><fieldset disabled={busy}>
   <label className="field">유튜브 주소<input type="url" required maxLength={1000} value={draft.youtube_url} placeholder="https://music.youtube.com/..." onChange={e=>setDraft({...draft,youtube_url:e.target.value})}/></label><button type="button" className="secondary" disabled={!youtubeSource(draft.youtube_url)||busy} onClick={()=>void preview()}>곡 정보 가져오기</button>
   <label className="field">추천 제목<input required maxLength={120} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label className="field">아티스트 · 채널<input maxLength={120} value={draft.artist} onChange={e=>setDraft({...draft,artist:e.target.value})}/></label><label className="field">추천 한마디<input maxLength={500} placeholder="예: 마지막 한 세트까지 밀어주는 힙합" value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label>
   <div><h3>다른 음악 앱 링크</h3><p className="muted">Spotify, Apple Music, 멜론 등 같은 곡·플리의 공유 주소를 추가하세요. 목록에 없는 앱도 이름을 직접 넣을 수 있어요.</p></div>
   <datalist id="music-services">{musicServices.filter(x=>x!=='YouTube Music').map(x=><option key={x} value={x}/>)}</datalist>
   {draft.links.map((link,i)=><div className="music-link-edit" key={i}><label className="field">앱 이름<input list="music-services" required maxLength={40} value={link.service} onChange={e=>setDraft({...draft,links:draft.links.map((x,j)=>j===i?{...x,service:e.target.value}:x)})}/></label><label className="field">곡·플리 공유 주소<input type="url" required value={link.url} onChange={e=>setDraft({...draft,links:draft.links.map((x,j)=>j===i?{...x,url:e.target.value}:x)})}/></label><button type="button" className="icon-button" aria-label={`${i+1}번 앱 링크 제거`} onClick={()=>setDraft({...draft,links:draft.links.filter((_,j)=>j!==i)})}><X size={16}/></button></div>)}
   <button type="button" className="secondary" disabled={draft.links.length>=30} onClick={()=>setDraft({...draft,links:[...draft.links,{service:'',url:''}]})}><Plus size={16}/>다른 앱 링크 추가</button>
   {draft.id&&<button type="button" className="danger" onClick={()=>{setRemove(draft);setDraft(null);}}>추천에서 내리기</button>}
  </fieldset>{formError&&<p className="form-error" role="alert">{formError}</p>}<button className="primary" disabled={busy}>{busy?'처리 중…':'추천 저장'}</button></form>}</DialogContent></Dialog>
  <Dialog open={!!remove} onOpenChange={v=>!v&&!busy&&setRemove(null)}><DialogContent className="app-dialog"><DialogTitle>추천에서 내릴까요?</DialogTitle><DialogDescription>{remove?.title} 항목이 공개 목록에서 숨겨집니다.</DialogDescription>{formError&&<p role="alert">{formError}</p>}<button className="danger" disabled={busy} onClick={async()=>{if(!remove)return;setBusy(true);setFormError('');try{await post({action:'archive',id:remove.id,revision:remove.revision});setRemove(null);await load();}catch(e){setFormError((e as Error).message);}finally{setBusy(false);}}}>추천에서 내리기</button></DialogContent></Dialog>
 </section>;
}
