'use client';
import {useEffect,useState} from 'react';
import type {Snapshot} from '@/lib/gym-model';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
export function NotificationCheck(){const [deviceStatus,setDeviceStatus]=useState('기기 상태 확인 중…');useEffect(()=>{const supported='serviceWorker'in navigator&&'Notification'in window&&'PushManager'in window;if(!supported){setDeviceStatus('이 환경은 웹 푸시를 지원하지 않아요.');return;}void navigator.serviceWorker.getRegistration('/').then(r=>r?.pushManager.getSubscription()).then(s=>setDeviceStatus(`알림 권한: ${Notification.permission==='granted'?'허용':Notification.permission==='denied'?'차단':'미설정'} · 현재 기기: ${s?'구독됨':'등록 필요'}`)).catch(()=>setDeviceStatus('기기 상태를 확인하지 못했어요.'));},[]);const [status,setStatus]=useState(''),[busy,setBusy]=useState(false),[received,setReceived]=useState(false);async function send(action:string){setBusy(true);try{if(!('serviceWorker'in navigator)||!('Notification'in window))throw Error('이 브라우저는 지원하지 않아요. 아이폰은 홈 화면에 설치한 SPOT에서 열어주세요.');if(Notification.permission!=='granted')throw Error('기기 알림 권한이 꺼져 있어요. 브라우저·휴대폰 설정에서 SPOT 알림을 허용해주세요.');const sub=await(await navigator.serviceWorker.getRegistration('/'))?.pushManager.getSubscription();if(!sub)throw Error('위의 ‘이 기기에 푸시 알림 켜기’를 먼저 눌러주세요.');const r=await fetch('/api/notifications/test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,endpoint:sub.endpoint})});const d=await r.json() as {error?:string;message?:string};if(!r.ok)throw Error(d.error);setStatus(d.message||'처리했어요.');if(action==='received')setReceived(true);}catch(e){setStatus((e as Error).message);}finally{setBusy(false);}}return <div className="product-help"><p className="muted">{deviceStatus}</p><div className="button-row"><button className="secondary" disabled={busy} onClick={()=>void send('send')}>테스트 알림 보내기</button><button className="text-button" disabled={busy||received} onClick={()=>void send('received')}>{received?'수신 확인됨':'알림을 받았어요'}</button></div>{status&&<p role="status">{status}</p>}<p className="muted">알림이 안 오면 휴대폰의 SPOT 알림 허용·집중 모드·절전 설정을 확인하세요. 서버 접수와 실제 기기 표시는 다릅니다.</p></div>;}
export function GettingStarted({data,onCrew,onSchedule,onRoutines,onMissions,onNotifications}:{data:Snapshot;onCrew:()=>void;onSchedule:()=>void;onRoutines:()=>void;onMissions:()=>void;onNotifications:()=>void}){
 const steps=[
  {title:'친구들과 연결',description:'크루를 만들거나 초대 링크로 합류하세요. 여러 크루에 함께 가입할 수 있어요.',action:'크루 열기',run:onCrew},
  {title:'내 루틴 준비',description:'공통 루틴을 가져오거나 글·사진으로 만들어요. 이름이 낯설면 ‘그림으로 운동 찾기’를 이용하세요.',action:'루틴 보기',run:onRoutines},
  {title:'요일과 시간 정하기',description:'운동 일정에서 날짜와 시간을 정하고 참여하세요. 반복 일정으로 매주 같은 약속도 만들 수 있어요.',action:'일정 보기',run:onSchedule},
  {title:'운동하고 돌아보기',description:'루틴 카드에서 운동을 시작하고 끝낸 세트를 체크하세요. ‘기록·분석’에서 지난 운동을 확인하고 수정할 수 있어요.',action:'운동 시작하러 가기',run:onRoutines},
 ];
 return <section className="panel dashboard-guide" aria-label="SPOT 사용 가이드">
  <details>
   <summary><span><span className="guide-kicker">QUICK GUIDE</span><strong>어디서 시작할지 막막하다면</strong><small>크루 → 루틴 → 일정 → 운동 · 사용법 펼치기</small></span><span className="guide-toggle" aria-hidden="true">＋</span></summary>
   <div className="guide-content">
    <p className="guide-context">{data.crew?`${data.crew.name}에서 함께하고 있어요. 필요한 단계부터 시작하세요.`:data.user?'먼저 크루를 만들거나 친구의 초대 링크로 합류해보세요.':'로그인하면 친구들과 일정과 루틴을 저장할 수 있어요.'}</p>
    <ol className="guide-steps">{steps.map((step,i)=><li key={step.title}><span className="guide-number">0{i+1}</span><div><h3>{step.title}</h3><p>{step.description}</p><button type="button" className="text-button" onClick={step.run}>{step.action} →</button></div></li>)}</ol>
    <div className="guide-extras"><button type="button" className="secondary" onClick={onNotifications}>운동 전 알림 설정</button><button type="button" className="secondary" onClick={onMissions}>친구들과 미션 도전</button></div>
    <details className="guide-faq"><summary>사용 전에 알아두면 좋아요</summary><dl>
     <dt>공통 루틴과 내 루틴은 뭐가 달라요?</dt><dd>공통 루틴 수정은 같은 크루에 반영돼요. 나에게만 맞추려면 개인 수정본을 만들어 사용하세요.</dd>
     <dt>운동 기록을 남기면 출석도 되나요?</dt><dd>운동 기록은 나만 보는 기록이고, 크루 출석 체크는 별도예요. 미션에 참여했다면 출석도 확인하세요.</dd>
     <dt>앱을 닫아도 알림이 오나요?</dt><dd>알림 설정에서 이 기기의 푸시를 켜고 테스트 알림을 확인하세요. 운동 전 알림을 설정해도 기기 권한·절전 설정에 따라 수신이 달라질 수 있어요.</dd>
     <dt>분석에 안내가 안 나와요.</dt><dd>비교할 기록이나 운동 조건이 부족하면 판단을 보류해요. 실제 수행한 무게·횟수와 운동 조건을 남겨주세요.</dd>
    </dl></details>
   </div>
  </details>
 </section>;
}
export function UsagePanel({userId}:{userId?:string}){const [admin,setAdmin]=useState(false),[open,setOpen]=useState(false),[counts,setCounts]=useState<Record<string,number>|null>(null),[error,setError]=useState('');useEffect(()=>{let live=true;try{let id=localStorage.getItem('spot-visitor');if(!id){id=crypto.randomUUID();localStorage.setItem('spot-visitor',id);}void fetch('/api/usage',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({visitorId:id})}).catch(()=>{});}catch{}void fetch('/api/music').then(r=>r.json()).then(d=>{if(live)setAdmin(!!(d as {admin:boolean}).admin);}).catch(()=>{});return()=>{live=false;};},[userId]);async function show(){setOpen(true);setError('');try{const r=await fetch('/api/usage');const d=await r.json() as Record<string,number>&{error?:string};if(!r.ok)throw Error(d.error);setCounts(d);}catch(e){setError((e as Error).message);}}if(!admin)return null;return <><button className="text-button" onClick={()=>void show()}>이용 통계</button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="app-dialog"><DialogTitle>SPOT 이용 통계</DialogTitle><DialogDescription>방문은 이 기능을 켠 이후부터 브라우저별로 집계합니다. IP·방문 URL·초대 토큰은 저장하지 않습니다.</DialogDescription>{error&&<p role="alert">{error}</p>}{counts&&<div className="usage-grid">{Object.entries({visitors:'누적 방문 브라우저',today:'오늘 방문',returning:'다른 날 재방문',accounts:'로그인 계정',joined:'크루 가입자',participating:'일정 참여자',attended:'확인된 출석자'}).map(([key,label])=><div key={key}><span>{label}</span><strong>{counts[key]??0}</strong></div>)}</div>}<p className="muted">동일 사람이 다른 기기를 사용하면 방문 수가 나뉩니다. 계정·가입·참여 수는 DB 전체 기준이며 날짜별 전환율은 아닙니다.</p></DialogContent></Dialog></>;}
