'use client';
import {useEffect,useState} from 'react';
import {MessageSquare,Plus,ExternalLink} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import type {GuideRequestSummary} from '@/lib/guide-request-model';
import type {Suggestion} from '@/lib/suggestions';
import './suggestion-box.css';
const categories={feature:'기능 개선',music:'음악 · 플레이리스트',bug:'오류 제보',other:'기타',guide:'운동 가이드'};
const statuses={received:'접수',reviewing:'검토 중',planned:'반영 예정',done:'반영 완료',closed:'검토 종료'};
type Draft={id:string;category:keyof typeof categories;title:string;body:string;link:string};
export function SuggestionBox({userId,signInHref}:{userId?:string;signInHref:string}){
 const [open,setOpen]=useState(false),[items,setItems]=useState<Suggestion[]>([]),[admin,setAdmin]=useState(false),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [guides,setGuides]=useState<GuideRequestSummary[]>([]),[guideFilter,setGuideFilter]=useState('');
 const [draft,setDraft]=useState<Draft|null>(null),[selected,setSelected]=useState<Suggestion|null>(null),[filter,setFilter]=useState('all');
 useEffect(()=>{setItems([]);setGuides([]);setGuideFilter('');setAdmin(false);setSelected(null);setDraft(null);setOpen(false);},[userId]);
 async function load(guide=guideFilter){setLoading(true);setError('');try{const r=await fetch('/api/suggestions'+(guide?'?guide='+encodeURIComponent(guide):''),{cache:'no-store'});const data=await r.json() as {items:Suggestion[];admin:boolean;guides:GuideRequestSummary[];error?:string};if(!r.ok)throw Error(data.error);setItems(data.items);setGuides(data.guides??[]);setGuideFilter(guide);setAdmin(data.admin);if(!data.admin)setDraft(current=>current??{id:crypto.randomUUID(),category:'feature',title:'',body:'',link:''});}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 async function save(action:'create'|'update',item:unknown){setBusy(true);setError('');try{const r=await fetch('/api/suggestions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,item})});const data=await r.json() as {error?:string};if(!r.ok)throw Error(data.error);setDraft(null);setSelected(null);setNotice(action==='create'?'건의를 보냈어요. 관리자가 확인 후 업데이트에 참고할게요.':'답변과 상태를 저장했어요.');await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function start(){setError('');setNotice('');setSelected(null);setDraft({id:crypto.randomUUID(),category:'feature',title:'',body:'',link:''});}
 const shown=items.filter(i=>filter==='all'||i.status===filter);
 return <><button className="icon-button" aria-label="건의함" title="건의함 · 음악 추천 요청" onClick={()=>{setOpen(true);setNotice('');if(userId)void load('');}}><MessageSquare size={19}/></button>
 <Dialog open={open} onOpenChange={v=>{if(!busy)setOpen(v);}}><DialogContent className="app-dialog suggestion-dialog"><DialogTitle>{draft?'건의사항 남기기':selected?'건의 상세':admin?'건의함 관리':'건의함'}</DialogTitle><DialogDescription>불편한 점이나 듣고 싶은 음악을 알려주세요. 건의 내용은 관리자만 확인할 수 있어요.</DialogDescription>
 {!userId?<a className="primary" href={signInHref}>로그인하고 건의하기</a>:draft?<form className="form-stack" onSubmit={e=>{e.preventDefault();void save('create',draft);}}><fieldset disabled={busy}>
 <label className="field">종류<select value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value as Draft['category']})}>{Object.entries(categories).map(([key,name])=><option key={key} value={key}>{name}</option>)}</select></label>
 <label className="field">제목<input required maxLength={100} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} placeholder="예: 하체 운동용 플레이리스트 추천"/></label>
 <label className="field">내용<textarea required rows={5} maxLength={3000} value={draft.body} onChange={e=>setDraft({...draft,body:e.target.value})} placeholder="어떤 점이 바뀌면 좋을까요? 음악은 원하는 분위기도 알려주세요."/></label>
 <label className="field">참고 · 음악 링크 (선택)<input type="url" maxLength={2000} value={draft.link} onChange={e=>setDraft({...draft,link:e.target.value})} placeholder="https://music.youtube.com/..."/></label>
 </fieldset><button className="primary" disabled={busy}>{busy?'보내는 중…':'건의 남기기'}</button><button type="button" className="text-button" disabled={busy} onClick={()=>admin?setDraft(null):setOpen(false)}>{admin?'목록으로':'닫기'}</button></form>:selected?<div className="suggestion-detail"><span className="status-chip">{categories[selected.category]} · {statuses[selected.status]}</span><h3>{selected.title}</h3><p className="muted">{selected.author_name} · {new Date(Number(selected.created_at)).toLocaleDateString('ko-KR')}</p><p className="suggestion-body">{selected.body}</p>{selected.link&&<a className="secondary" href={selected.link} target="_blank" rel="noopener noreferrer">참고 링크 열기<ExternalLink size={15}/></a>}
 {admin?<form className="form-stack" onSubmit={e=>{e.preventDefault();void save('update',selected);}}><fieldset disabled={busy}><label className="field">처리 상태<select value={selected.status} onChange={e=>setSelected({...selected,status:e.target.value as Suggestion['status']})}>{Object.entries(statuses).map(([key,name])=><option key={key} value={key}>{name}</option>)}</select></label><label className="field">관리자 답변<textarea rows={4} maxLength={3000} value={selected.reply} onChange={e=>setSelected({...selected,reply:e.target.value})}/></label></fieldset><button className="primary" disabled={busy}>답변 · 상태 저장</button></form>:<div className="suggestion-reply"><strong>관리자 답변</strong><p className="suggestion-body">{selected.reply||'아직 답변이 없어요. 확인 후 여기에 남겨드릴게요.'}</p></div>}
 <button className="text-button" disabled={busy} onClick={()=>setSelected(null)}>목록으로</button></div>:<><div className="section-line"><button className="secondary" onClick={start}><Plus size={16}/>건의 남기기</button><button className="text-button" disabled={loading} onClick={()=>void load()}>새로고침</button></div>{admin&&guides.length>0&&<details className="guide-request-ranking"><summary>운동 가이드 요청 · 요청 많은 순</summary>{guides.map(g=><button type="button" className="suggestion-item" key={g.title} onClick={()=>{setFilter('all');void load(g.title);}}><strong>{g.title}</strong><small>{g.people}명 요청 · 미처리 {g.requests}건</small></button>)}</details>}{guideFilter&&<button type="button" className="text-button" onClick={()=>void load('')}>{guideFilter} 요청 보는 중 · 전체 건의로</button>}<label className="field">처리 상태 필터<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">전체</option>{Object.entries(statuses).map(([key,name])=><option key={key} value={key}>{name}</option>)}</select></label>{loading?<p role="status">불러오는 중…</p>:<div className="suggestion-list">{shown.length?shown.map(i=><button key={i.id} className="suggestion-item" onClick={()=>{setError('');setNotice('');setSelected({...i});}}><span className="status-chip">{categories[i.category]} · {statuses[i.status]}</span><strong>{i.title}</strong><small>{admin?`${i.author_name} · `:''}{new Date(Number(i.created_at)).toLocaleDateString('ko-KR')}{i.reply?' · 답변 있음':''}</small></button>):<p className="muted">{items.length?'해당 상태의 건의가 없어요.':'아직 건의가 없어요. 첫 의견을 남겨주세요.'}</p>}</div>}<p className="muted">최근 100개 건의를 표시합니다.</p></>}
 {notice&&<p className="suggestion-notice" role="status">{notice}</p>}{error&&<p className="form-error" role="alert">{error}</p>}
 </DialogContent></Dialog></>;
}
