 'use client';
import {useEffect,useState} from 'react';
import type {JournalEntry} from '@/lib/training-journal';
import {localDate} from '@/lib/gym-model';
const labels={body:'신체',meal:'식단',cardio:'유산소',recovery:'컨디션'};
const newContent=(kind:JournalEntry['content']['kind']):JournalEntry['content']=>kind==='body'?{kind,weight:null,fat:null,muscle:null,note:''}:kind==='meal'?{kind,name:'',meal:'lunch',calories:null,protein:null,carbs:null,fat:null,note:''}:kind==='cardio'?{kind,name:'걷기',minutes:30,distance:null,note:''}:{kind,sleep:null,energy:null,soreness:null,note:''};
const fields={body:[['weight','체중 kg',500],['fat','체지방률 %',100],['muscle','골격근량 kg',200]],meal:[['calories','열량 kcal',10000],['protein','단백질 g',1000],['carbs','탄수화물 g',2000],['fat','지방 g',1000]],cardio:[['minutes','시간 분',1440],['distance','거리 km',1000]],recovery:[['sleep','수면 시간',24],['energy','활력 1–5',5],['soreness','근육통 0–5',5]]} as const;
export function TrainingJournal(){
 const [entries,setEntries]=useState<JournalEntry[]>([]),[cursor,setCursor]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[kind,setKind]=useState<JournalEntry['content']['kind']>('body');
 const [draft,setDraft]=useState<JournalEntry|null>(null),[undo,setUndo]=useState<{id:string;revision:number}|null>(null);
 async function load(more=false){setBusy(true);setError('');try{const r=await fetch('/api/journal'+(more&&cursor?'?cursor='+encodeURIComponent(cursor):''),{cache:'no-store'});const d=await r.json() as {entries:JournalEntry[];cursor:string|null;error?:string};if(!r.ok)throw Error(d.error);setEntries(old=>more?[...old,...d.entries.filter((e:JournalEntry)=>!old.some(x=>x.id===e.id))]:d.entries);setCursor(d.cursor);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{void load();},[]); // Mounted only inside the authenticated personal history dialog.
 async function act(payload:unknown){setBusy(true);setError('');try{const r=await fetch('/api/journal',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json() as {id:string;revision:number;entry?:JournalEntry;error?:string};if(!r.ok)throw Error(d.error);return d;}catch(e){setError((e as Error).message);return null;}finally{setBusy(false);}}
 function create(){setDraft({id:crypto.randomUUID(),date:localDate(),content:newContent(kind),revision:0});setMessage('');}
 const visible=entries.filter(e=>e.content.kind===kind),today=localDate(),meals=entries.filter(e=>e.content.kind==='meal'&&e.date===today),bodies=entries.filter(e=>e.content.kind==='body').slice().reverse();
 return <div className="form-stack"><div className="training-subnav" aria-label="생활 기록 종류">{Object.entries(labels).map(([k,l])=><button className="secondary" key={k} aria-pressed={kind===k} onClick={()=>{setKind(k as typeof kind);setDraft(null);}}>{l}</button>)}</div><p className="muted">직접 측정하거나 영양표에서 확인한 값을 기록하세요. 빈 값은 0으로 추정하지 않아요.</p>
 {error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}{busy&&<p role="status">처리 중…</p>}
 {kind==='meal'&&<section className="training-advice"><h3>오늘 입력한 식단 합계</h3>{(['calories','protein','carbs','fat'] as const).map((key,i)=>{const values=meals.flatMap(e=>e.content.kind==='meal'&&e.content[key]!==null?[e.content[key]!]:[]);return <p key={key}>{['열량','단백질','탄수화물','지방'][i]}: {values.length?values.reduce((a,b)=>a+b,0).toLocaleString():'미기록'} {i===0?'kcal':'g'} · {values.length}/{meals.length}건 입력</p>;})}<small>목록을 더 불러오기 전에는 현재 불러온 기록 기준입니다.</small></section>}
 {kind==='body'&&bodies.length>1&&<section><h3>측정 변화</h3><div className="training-table-scroll"><table><thead><tr><th>날짜</th><th>체중 kg</th><th>체지방 %</th><th>골격근 kg</th></tr></thead><tbody>{bodies.slice(-12).map(e=><tr key={e.id}><td>{e.date}</td>{e.content.kind==='body'&&<><td>{e.content.weight??'—'}</td><td>{e.content.fat??'—'}</td><td>{e.content.muscle??'—'}</td></>}</tr>)}</tbody></table></div></section>}
 {!draft?<button className="primary" disabled={busy} onClick={create}>{labels[kind]} 기록 추가</button>:<form className="form-stack training-advice" onSubmit={async e=>{e.preventDefault();const result=await act({action:'save',entry:draft});if(result){setDraft(null);setMessage('기록을 저장했어요.');await load();}}}>
 <label className="field">기록 날짜<input required type="date" value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/></label>
 {'name' in draft.content&&<label className="field">{kind==='meal'?'음식 · 분량':'운동 이름'}<input required maxLength={120} value={draft.content.name} placeholder={kind==='meal'?'예: 현미밥 1공기 + 닭가슴살 100g':'예: 러닝'} onChange={e=>setDraft({...draft,content:{...draft.content,name:e.target.value} as JournalEntry['content']})}/></label>}
 {draft.content.kind==='meal'&&<label className="field">식사<select value={draft.content.meal} onChange={e=>setDraft({...draft,content:{...draft.content,meal:e.target.value} as JournalEntry['content']})}>{[['breakfast','아침'],['lunch','점심'],['dinner','저녁'],['snack','간식·보충제']].map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label>}
 <div className="journal-fields">{fields[draft.content.kind].map(([key,label,max])=><label className="field" key={key}>{label}<input type="number" inputMode="decimal" min={key==='minutes'?0.1:key==='energy'?1:0} max={max} step={key==='energy'||key==='soreness'?1:'any'} value={(draft.content as unknown as Record<string,number|null>)[key]??''} onChange={e=>setDraft({...draft,content:{...draft.content,[key]:e.target.value===''?null:Number(e.target.value)} as JournalEntry['content']})}/></label>)}</div><label className="field">메모<textarea rows={2} maxLength={500} value={draft.content.note} onChange={e=>setDraft({...draft,content:{...draft.content,note:e.target.value}})}/></label><div className="button-row"><button className="primary" disabled={busy} type="submit">저장</button><button className="secondary" type="button" disabled={busy} onClick={()=>setDraft(null)}>취소</button></div></form>}
 {undo&&<button className="secondary" disabled={busy} onClick={async()=>{if(await act({action:'restore',...undo})){setUndo(null);await load();}}}>방금 숨긴 기록 되돌리기</button>}
 {visible.map(e=><article className="training-advice" key={e.id}><strong>{e.date} · {'name'in e.content?e.content.name:labels[e.content.kind]}</strong><p>{fields[e.content.kind].map(([k,l])=>`${l}: ${(e.content as unknown as Record<string,number|null>)[k]??'—'}`).join(' · ')}</p>{e.content.note&&<p>{e.content.note}</p>}<div className="button-row"><button className="text-button" disabled={busy} onClick={()=>setDraft(structuredClone(e))}>수정</button><button className="text-button" disabled={busy} onClick={()=>setDraft({...structuredClone(e),id:crypto.randomUUID(),date:today,revision:0})}>오늘로 복사</button><button className="text-button" disabled={busy} onClick={async()=>{const r=await act({action:'archive',id:e.id,revision:e.revision});if(r){setUndo(r);await load();}}}>숨기기</button></div></article>)}{!visible.length&&!busy&&<p className="muted">아직 {labels[kind]} 기록이 없어요.</p>}{cursor&&<button disabled={busy} className="secondary" onClick={()=>void load(true)}>이전 생활 기록 더 보기</button>}
 </div>;
}
