 'use client';
import {useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {buildTrainingProgram,type ProgramOptions} from '@/lib/training-programs';
import type {Routine} from '@/lib/gym-model';
export function TrainingPrograms({requireCrew,onImport}:{requireCrew:()=>boolean;onImport:(routines:Omit<Routine,'version'>[])=>Promise<boolean>}){
 const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[options,setOptions]=useState<ProgramOptions>({split:'fullbody',goal:'consistency',equipment:'gym',experience:'beginner'}),[draft,setDraft]=useState<Omit<Routine,'version'>[]|null>(null),[error,setError]=useState('');
 return <><button className="secondary" onClick={()=>{if(requireCrew()){setOpen(true);setDraft(null);setError('');}}}>목표별 프로그램</button><Dialog open={open} onOpenChange={v=>{if(!busy)setOpen(v);}}><DialogContent className="app-dialog"><DialogTitle>내 조건으로 프로그램 구성</DialogTitle><DialogDescription>SPOT이 만든 구성 예시입니다. 목표·장비에 맞춰 초안을 만들고 저장 전에 검토하세요.</DialogDescription><div className="form-stack"><label className="field">분할<select value={options.split} onChange={e=>{setDraft(null);setOptions({...options,split:e.target.value as ProgramOptions['split']});}}><option value="fullbody">전신 A/B</option><option value="upperlower">상체 / 하체</option><option value="ppl">PUSH / PULL / LEGS</option></select></label><label className="field">목표<select value={options.goal} onChange={e=>{setDraft(null);setOptions({...options,goal:e.target.value as ProgramOptions['goal']});}}><option value="consistency">꾸준한 운동 습관</option><option value="hypertrophy">근육 성장</option><option value="strength">근력 중심</option></select></label><label className="field">장비<select value={options.equipment} onChange={e=>{setDraft(null);setOptions({...options,equipment:e.target.value as ProgramOptions['equipment']});}}><option value="gym">헬스장 머신·프리웨이트</option><option value="home">홈트 · 덤벨과 벤치 있음</option></select></label><label className="field">경험<select value={options.experience} onChange={e=>{setDraft(null);setOptions({...options,experience:e.target.value as ProgramOptions['experience']});}}><option value="beginner">동작을 배우는 중</option><option value="experienced">동작을 익혀 꾸준히 훈련 중</option></select></label><button className="secondary" onClick={()=>setDraft(buildTrainingProgram(options))}>구성 미리보기</button>{draft&&<>{draft.map((r,i)=><section className="training-advice" key={r.id}><label className="field">루틴 이름<input maxLength={60} value={r.name} onChange={e=>setDraft(draft.map((x,j)=>j===i?{...x,name:e.target.value}:x))}/></label><p>{r.subtitle}</p>{r.exercises.map(e=><p key={e.id}>{e.name} · {e.sets}세트 × {e.durationSeconds?`${e.durationSeconds}초`:`${e.reps}회`}</p>)}<p className="muted">{r.notes}</p></section>)}<p>선택한 크루의 공통 루틴에 {draft.length}개를 추가합니다. 저장 후 종목·세트·요일을 편집할 수 있어요.</p><button className="primary" disabled={busy||draft.some(r=>!r.name.trim())} onClick={async()=>{setBusy(true);try{if(await onImport(draft))setOpen(false);else setError('저장하지 못했어요. 크루의 변경 상태를 확인하고 다시 시도하세요.');}catch{setError('프로그램 저장에 실패했어요.');}finally{setBusy(false);}}}>{busy?'저장 중…':'이 구성으로 공통 루틴 추가'}</button></>}{error&&<p role="alert">{error}</p>}</div></DialogContent></Dialog></>;
}
