 'use client';
import {useState} from 'react';
import type {ExerciseLog,WorkoutSet} from '@/lib/training-model';
export function TrainingQuickSet({exercise,busy,onChange,onApply,onComplete}:{exercise:ExerciseLog;busy:boolean;onChange:(id:string,patch:Partial<WorkoutSet>)=>void;onApply:(id:string)=>void;onComplete:(set:WorkoutSet)=>void}){
 const [step,setStep]=useState(2.5);const next=exercise.sets.find(s=>!s.done);if(!next)return <p className="training-save-status">이 운동의 세트를 모두 완료했어요.</p>;
 const index=exercise.sets.findIndex(s=>s.id===next.id)+1;
 const adjust=(field:'weight'|'reps'|'seconds',delta:number)=>{const value=next[field];if(value===null)return;onChange(next.id,{[field]:Math.round(Math.max(field==='weight'?0:1,Math.min(field==='weight'?1500:field==='seconds'?3600:100,value+delta))*100)/100});};
 return <details className="quick-set" open><summary>다음 {index}세트 · 빠른 입력</summary><p className="muted">{exercise.timed?`${next.seconds??'미입력'}초`:`${next.weight??'미입력'}kg × ${next.reps??'미입력'}회`} · {next.kind==='warmup'?'웜업':next.kind==='drop'?'드롭':next.kind==='failure'?'실패':'본세트'}</p>{!exercise.timed&&<><label className="field">중량 조절 단위<select disabled={busy} value={step} onChange={e=>setStep(Number(e.target.value))}>{[0.5,1,1.25,2.5,5].map(v=><option value={v} key={v}>{v}kg</option>)}</select></label><div className="button-row"><button type="button" className="secondary" disabled={busy||next.weight===null} onClick={()=>adjust('weight',-step)}>− {step}kg</button><button type="button" className="secondary" disabled={busy||next.weight===null} onClick={()=>adjust('weight',step)}>+ {step}kg</button></div>{next.weight===null&&<small>중량은 아래 세트 칸에서 먼저 입력해주세요.</small>}</>}<div className="button-row"><button type="button" className="secondary" disabled={busy} onClick={()=>adjust(exercise.timed?'seconds':'reps',exercise.timed?-5:-1)}>{exercise.timed?'− 5초':'− 1회'}</button><button type="button" className="secondary" disabled={busy} onClick={()=>adjust(exercise.timed?'seconds':'reps',exercise.timed?5:1)}>{exercise.timed?'+ 5초':'+ 1회'}</button><button type="button" className="primary" disabled={busy} onClick={()=>onComplete(next)}>{index}세트 완료</button></div><button type="button" className="text-button" disabled={busy||!exercise.sets.some(s=>s.id!==next.id&&!s.done&&s.kind===next.kind)} onClick={()=>onApply(next.id)}>같은 종류의 미완료 세트에 이 값 적용</button><small>완료한 세트와 다른 종류의 세트는 유지해요. RIR은 복사하지 않아요.</small></details>;
}
