 'use client';
import {useState} from 'react';
import type {ExerciseLog,WorkoutSet} from '@/lib/training-model';
export function TrainingQuickSet({exercise,busy,onChange,onApply,onComplete,onNext}:{exercise:ExerciseLog;busy:boolean;onNext?:()=>void;onChange:(id:string,patch:Partial<WorkoutSet>)=>void;onApply:(id:string)=>void;onComplete:(set:WorkoutSet)=>void}){
 const [step,setStep]=useState(2.5);const next=exercise.sets.find(s=>!s.done);if(!next)return <section className="quick-set quick-set-v2"><h3>이 운동을 마쳤어요.</h3>{onNext?<button className="primary focus-complete" disabled={busy} onClick={onNext}>다음 운동으로</button>:<p>아래에서 컨디션을 확인하고 운동을 종료하세요.</p>}</section>;
 const index=exercise.sets.findIndex(s=>s.id===next.id)+1;
 const adjust=(field:'weight'|'reps'|'seconds',delta:number)=>{const value=next[field];if(value===null)return;onChange(next.id,{[field]:Math.round(Math.max(field==='weight'?0:1,Math.min(field==='weight'?1500:field==='seconds'?3600:100,value+delta))*100)/100});};
 return <section className="quick-set quick-set-v2" aria-label={`현재 ${index}세트`}><div className="quick-set-title"><span>CURRENT SET</span><strong>{index}<small> / {exercise.sets.length}</small></strong></div><div className="focus-set-inputs">{!exercise.timed&&<label>중량 · kg<input aria-label="현재 세트 중량 kg" disabled={busy} type="number" inputMode="decimal" min={0} max={1500} step="any" placeholder="미입력" value={next.weight??''} onChange={e=>onChange(next.id,{weight:e.target.value===''?null:Number(e.target.value)})}/></label>}<label>{exercise.timed?'시간 · 초':'반복 · 회'}<input aria-label={exercise.timed?'현재 세트 시간 초':'현재 세트 횟수'} disabled={busy} type="number" inputMode="numeric" min={1} max={exercise.timed?3600:100} value={(exercise.timed?next.seconds:next.reps)??''} onChange={e=>onChange(next.id,{[exercise.timed?'seconds':'reps']:e.target.value===''?null:Number(e.target.value)})}/></label></div><div className="focus-step-row"><button type="button" className="secondary" disabled={busy||(exercise.timed?next.seconds:next.weight)===null} onClick={()=>adjust(exercise.timed?'seconds':'weight',exercise.timed?-5:-step)}>{exercise.timed?'− 5초':`− ${step}kg`}</button><button type="button" className="secondary" disabled={busy||(exercise.timed?next.seconds:next.weight)===null} onClick={()=>adjust(exercise.timed?'seconds':'weight',exercise.timed?5:step)}>{exercise.timed?'+ 5초':`+ ${step}kg`}</button></div><button type="button" className="primary focus-complete" disabled={busy} onClick={()=>onComplete(next)}>{index}세트 완료</button><details className="focus-options"><summary>여유 반복 수 · 일괄 입력</summary>{!exercise.timed&&<><label className="field">더 할 수 있었던 횟수 · RIR<input type="number" aria-label="현재 세트 RIR" min={0} max={10} disabled={busy} placeholder="모르면 비워두세요" value={next.rir??''} onChange={e=>onChange(next.id,{rir:e.target.value===''?null:Number(e.target.value)})}/></label><label className="field">중량 조절 단위<select disabled={busy} value={step} onChange={e=>setStep(Number(e.target.value))}>{[0.5,1,1.25,2.5,5].map(v=><option value={v} key={v}>{v}kg</option>)}</select></label></>}<button type="button" className="text-button" disabled={busy||!exercise.sets.some(s=>s.id!==next.id&&!s.done&&s.kind===next.kind)} onClick={()=>onApply(next.id)}>같은 종류의 미완료 세트에 적용</button><small>완료한 세트는 유지하고 RIR은 복사하지 않아요.</small></details></section>;
}
