 'use client';
import {useEffect,useState} from 'react';
import type {JournalEntry} from '@/lib/training-journal';
import {localDate} from '@/lib/gym-model';
const labels={body:'신체',meal:'식단',cardio:'유산소',recovery:'컨디션'};
const newContent=(kind:JournalEntry['content']['kind']):JournalEntry['content']=>kind==='body'?{kind,weight:null,fat:null,muscle:null,note:''}:kind==='meal'?{kind,name:'',meal:'lunch',calories:null,protein:null,carbs:null,fat:null,note:''}:kind==='cardio'?{kind,name:'걷기',minutes:30,distance:null,note:''}:{kind,sleep:null,energy:null,soreness:null,note:''};
const fields={body:[['weight','체중 kg',500],['fat','체지방률 %',100],['muscle','골격근량 kg',200]],meal:[['calories','열량 kcal',10000],['protein','단백질 g',1000],['carbs','탄수화물 g',2000],['fat','지방 g',1000]],cardio:[['minutes','시간 분',1440],['distance','거리 km',1000]],recovery:[['sleep','수면 시간',24],['energy','활력 1–5',5],['soreness','근육통 0–5',5]]} as const;
export function TrainingJournal({initialKind='body',hideNavigation=false,onSaved,onDraftChange}:{initialKind?:JournalEntry['content']['kind'];hideNavigation?:boolean;onSaved?:()=>void;onDraftChange?:(dirty:boolean)=>void}={}){
 const [entries,setEntries]=useState<JournalEntry[]>([]),[cursor,setCursor]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[kind,setKind]=useState<JournalEntry['content']['kind']>(initialKind);
 const [draft,setDraft]=useState<JournalEntry|null>(null),[undo,setUndo]=useState<{id:string;revision:number}|null>(null);
 async function load(more=false){setBusy(true);setError('');try{const r=await fetch('/api/journal?kind='+kind+(more&&cursor?'&cursor='+encodeURIComponent(cursor):''),{cache:'no-store'});const d=await r.json() as {entries:JournalEntry[];cursor:string|null;error?:string};if(!r.ok)throw Error(d.error);setEntries(old=>more?[...old,...d.entries.filter((e:JournalEntry)=>!old.some(x=>x.id===e.id))]:d.entries);setCursor(d.cursor);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{void load();},[kind]);
 useEffect(()=>{onDraftChange?.(draft!==null);},[draft,onDraftChange]); // Mounted only after the parent verifies the authenticated journal endpoint.
 async function act(payload:unknown){setBusy(true);setError('');try{const r=await fetch('/api/journal',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json() as {id:string;revision:number;entry?:JournalEntry;error?:string};if(!r.ok)throw Error(d.error);return d;}catch(e){setError((e as Error).message);return null;}finally{setBusy(false);}}
 function create(){setDraft({id:crypto.randomUUID(),date:localDate(),content:newContent(kind),revision:0});setMessage('');}
 const visible=entries.filter(e=>e.content.kind===kind),today=localDate();
 const recentMeals=visible.filter(e=>e.content.kind==='meal').filter((e,i,all)=>all.findIndex(x=>x.content.kind==='meal'&&e.content.kind==='meal'&&x.content.name===e.content.name)===i).slice(0,6);
 const display=(e:JournalEntry)=>fields[e.content.kind].flatMap(([k,l])=>{const value=(e.content as unknown as Record<string,number|null>)[k];return value===null?[]:[`${l}: ${value}`];}).join(' · ')||'메모 기록';
 return <div className="form-stack">{!hideNavigation&&<div className="training-subnav" aria-label="생활 기록 종류">{Object.entries(labels).map(([k,l])=><button className="secondary" key={k} aria-pressed={kind===k} onClick={()=>{setKind(k as typeof kind);setDraft(null);}}>{l}</button>)}</div>}<p className="muted">직접 측정하거나 영양표에서 확인한 값을 기록하세요. 빈 값은 0으로 추정하지 않아요.</p>
 {error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}{busy&&<p role="status">처리 중…</p>}
 {!draft?<div className="journal-list-heading"><div><h3>내 {labels[kind]} 기록</h3><p className="health-caption">최근 기록부터 보여드려요.</p></div><button className="primary" disabled={busy} onClick={create}>+ 기록하기</button></div>:<form className="form-stack journal-form" onSubmit={async e=>{e.preventDefault();const result=await act({action:'save',entry:draft});if(result){setDraft(null);setMessage('기록을 저장했어요.');await load();onSaved?.();}}}>
 {kind==='meal'&&recentMeals.length>0&&<section className="journal-reuse"><h3>최근 식사에서 가져오기</h3><p className="health-caption">선택 후 분량과 영양값을 확인하고 저장하세요.</p><div>{recentMeals.map(e=><button className="secondary" type="button" key={e.id} onClick={()=>setDraft({...draft,content:structuredClone(e.content)})}>{e.content.kind==='meal'?e.content.name:''}</button>)}</div></section>}<label className="field">기록 날짜<input required type="date" value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/></label>
 {'name' in draft.content&&<label className="field">{kind==='meal'?'음식 · 분량':'운동 이름'}<input required maxLength={120} value={draft.content.name} placeholder={kind==='meal'?'예: 현미밥 1공기 + 닭가슴살 100g':'예: 러닝'} onChange={e=>setDraft({...draft,content:{...draft.content,name:e.target.value} as JournalEntry['content']})}/></label>}
 {draft.content.kind==='meal'&&<label className="field">식사<select value={draft.content.meal} onChange={e=>setDraft({...draft,content:{...draft.content,meal:e.target.value} as JournalEntry['content']})}>{[['breakfast','아침'],['lunch','점심'],['dinner','저녁'],['snack','간식·보충제']].map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label>}
 <div className="journal-fields">{fields[draft.content.kind].map(([key,label,max])=><label className="field" key={key}>{label}<input type="number" inputMode="decimal" min={key==='minutes'?0.1:key==='energy'?1:0} max={max} step={key==='energy'||key==='soreness'?1:'any'} value={(draft.content as unknown as Record<string,number|null>)[key]??''} onChange={e=>setDraft({...draft,content:{...draft.content,[key]:e.target.value===''?null:Number(e.target.value)} as JournalEntry['content']})}/></label>)}</div><label className="field">메모<textarea rows={2} maxLength={500} value={draft.content.note} onChange={e=>setDraft({...draft,content:{...draft.content,note:e.target.value}})}/></label><div className="button-row"><button className="primary" disabled={busy} type="submit">저장</button><button className="secondary" type="button" disabled={busy} onClick={()=>setDraft(null)}>취소</button>{draft.revision>0&&<button className="text-button" type="button" disabled={busy} onClick={async()=>{const r=await act({action:'archive',id:draft.id,revision:draft.revision});if(r){setUndo(r);setDraft(null);await load();onSaved?.();}}}>기록 숨기기</button>}</div></form>}
 {undo&&<button className="secondary" disabled={busy} onClick={async()=>{if(await act({action:'restore',...undo})){setUndo(null);await load();onSaved?.();}}}>방금 숨긴 기록 되돌리기</button>}
 {!draft&&<div className="journal-history-list">{visible.map(e=><article className="journal-history-row" key={e.id}><button className="journal-record-open" disabled={busy} onClick={()=>setDraft(structuredClone(e))}><span className="journal-record-date">{e.date}</span><strong>{'name'in e.content?e.content.name:labels[e.content.kind]+' 기록'}</strong><small>{display(e)}</small>{e.content.note&&<small>{e.content.note}</small>}</button><button className="text-button" aria-label={`${e.date} ${labels[kind]} 기록을 오늘로 복사`} disabled={busy} onClick={()=>setDraft({...structuredClone(e),id:crypto.randomUUID(),date:today,revision:0})}>오늘로 복사</button></article>)}{!visible.length&&!busy&&<p className="muted">아직 {labels[kind]} 기록이 없어요.</p>}{cursor&&<button disabled={busy} className="secondary" onClick={()=>void load(true)}>이전 기록 더 보기</button>}</div>}
 </div>;
}
