 'use client';
import {useState} from 'react';
import type {trainingInsights} from '@/lib/training-insights';
export function TrainingInsights({data}:{data:ReturnType<typeof trainingInsights>}){
 const [month,setMonth]=useState(()=>data.months[0]?.month??new Date().toISOString().slice(0,7));
 const m=data.months.find(m=>m.month===month),days=data.calendar.filter(d=>d.date.startsWith(month));
 return <div className="form-stack"><section><h3>최근 7일 리포트</h3><div className="training-metrics"><div><strong>{data.current.days}</strong><span>운동한 날 · 직전 7일 {data.previous.days}일</span></div><div><strong>{data.current.sets}</strong><span>완료 세트 · 직전 {data.previous.sets}세트</span></div><div><strong>{data.current.minutes}</strong><span>운동 분 · 수정 시간 우선</span></div></div><p className="muted">{data.current.sessions===0?'완료한 운동이 없어요. 다음 일정을 잡아보세요.':data.current.sets>data.previous.sets?'기록한 세트 수가 늘었어요. 같은 운동·기구인지 함께 확인하세요.':data.current.sets<data.previous.sets?'기록한 세트 수가 줄었어요. 계획된 휴식인지, 누락된 기록인지 확인하세요.':'기록한 세트 수가 직전 기간과 같아요. 운동별 변화를 함께 확인하세요.'}{data.current.missingWeights>0&&` 중량 미입력 ${data.current.missingWeights}세트는 중량 합계에 포함되지 않아요.`}</p><small className="muted">직접 수정한 운동 시간이 없으면 시작~완료 시간(휴식 포함)을 사용해요. 기록 기반 자동 요약입니다. 휴식·식단과 성과의 인과관계를 판정하지 않아요.</small></section>
 <details><summary>월간 리포트 · 운동 캘린더</summary><label className="field">월 선택<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label>{m?<p>{m.sessions}회 · {m.sets}세트 · 입력 중량 합계 {m.volume.toLocaleString()}kg·회{m.missingWeights?` · 중량 누락 ${m.missingWeights}세트`:''}</p>:<p>이 분석 기간에 해당 월의 기록이 없어요.</p>}<div className="training-calendar">{Array.from({length:new Date(Number(month.slice(0,4)),Number(month.slice(5,7)),0).getDate()||0},(_,i)=>{const date=month+'-'+String(i+1).padStart(2,'0'),count=days.find(d=>d.date===date)?.count??0;return <div key={date} className={count?'trained':''} title={`${date} · ${count}회`}><strong>{i+1}</strong><small>{count?`${count}회`:'—'}</small></div>;})}</div><small>분석은 최근 90일·최대 200회 기준이며 전체 기간은 기록 검색·백업에서 확인할 수 있어요.</small></details>
 <details><summary>부위별 운동량</summary><p className="muted">최근 7일 완료 세트를 운동 가이드의 부위 분류로 집계해요. 여러 부위가 함께 표시될 수 있으며 실제 근육 피로도·회복률은 아닙니다.</p>{data.body.length?data.body.map(b=><div className="body-load" key={b.name}><div><strong>{b.name}</strong><span>{b.sets}세트</span></div><meter min={0} max={Math.max(1,...data.body.map(x=>x.sets))} value={b.sets} aria-label={`${b.name} ${b.sets}세트`}/><small>마지막 기록 {new Date(b.last).toLocaleDateString('ko-KR',{timeZone:'Asia/Seoul'})}</small></div>):<p>최근 완료 세트가 없어요.</p>}</details>
 <details><summary>개인 최고 기록 · 추정 1RM</summary><p className="muted">같은 운동 이름·기구·중량 기준끼리 비교합니다. 추정 1RM은 총중량 기준 1–10회, RIR 0, 수행 조건 확인, 불편감 없음인 본세트·실패 세트만 사용해요. 이 조건은 SPOT의 필터이며 검증된 오차 보장은 아닙니다. 최대 반복을 억지로 시도할 필요는 없어요.</p>{data.records.map(r=><section className="training-advice" key={r.key}><strong>{r.name}</strong><p>{r.equipment} · 최고 입력 중량 {r.maxWeight}kg × {r.bestReps}회</p>{r.estimate?<><p>{r.estimate.measured?'기록된 단일 반복':'추정 1RM 공식 범위'}: {r.estimate.low}–{r.estimate.high}kg</p><small>Epley / Brzycki 두 공식의 차이이며 신뢰구간이 아닙니다.</small>{r.points.length>1&&<p>변화: {r.points.map(p=>`${new Date(p.date).toLocaleDateString('ko-KR',{timeZone:'Asia/Seoul',month:'numeric',day:'numeric'})} ${p.low}–${p.high}kg`).join(' → ')}</p>}</>:<p className="muted">추정 조건을 충족한 세트 없음</p>}</section>)}<a className="text-button" href="https://pubmed.ncbi.nlm.nih.gov/16937972/" target="_blank" rel="noopener noreferrer">반복 횟수와 1RM 예측 연구 ↗</a></details>
 <details><summary>3대 운동 합계</summary><p className="muted">최근 90일 확인된 스쿼트·벤치프레스·컨벤셔널 데드리프트 단일 반복(RIR 0) 총중량만 집계합니다. 변형 동작·기구·추정치와 섞지 않아요. 날짜가 서로 다를 수 있어 대회 기록은 아닙니다.</p>{Object.entries({squat:'스쿼트',bench:'벤치프레스',deadlift:'데드리프트'}).map(([k,label])=><p key={k}>{label}: {data.lifts[k as keyof typeof data.lifts]??'확인된 기록 없음'}{data.lifts[k as keyof typeof data.lifts]!==null?'kg':''}</p>)}<strong>{data.total===null?'세 종목 기록이 모이면 합계를 표시해요.':`합계 ${data.total}kg`}</strong></details>
 </div>;
}
