'use client';
import {useEffect,useRef,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import type {Routine} from '@/lib/gym-model';
import {loadLabels,workoutTotals,workoutStateSchema,type Workout,type WorkoutState,type ExerciseLog,type WorkoutSet} from '@/lib/training-model';
import {ExerciseLibrary,ExercisePreview} from './exercise-guide';
import {guideFor} from '@/lib/exercise-guides';
import './training.css';

async function request(payload:unknown){const r=await fetch('/api/workouts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await r.json() as {workout:Workout;error?:string;resumed?:boolean;carried?:number};if(!r.ok)throw Object.assign(Error(data.error||'저장에 실패했어요.'),{status:r.status});return data;}
export function RecordedWorkout({routine,userId,crewId,kind,sourceId}:{sourceId?:string;routine:Routine;userId:string;crewId:string;kind:'common'|'personal'}){
 const [open,setOpen]=useState(false),[workout,setWorkout]=useState<Workout|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState(''),[index,setIndex]=useState(0),[restUntil,setRestUntil]=useState(0),[remaining,setRemaining]=useState(0),[discard,setDiscard]=useState(false),[customName,setCustomName]=useState('');
 const current=useRef<Workout|null>(null),dirty=useRef(false),pending=useRef<Promise<boolean>|null>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null),flushRef=useRef<()=>Promise<boolean>>(async()=>true),blocked=useRef(false);
 const storageKey=`spot-workout-draft:${userId}`;
 function keep(w:Workout){try{localStorage.setItem(storageKey,JSON.stringify(w));}catch{setStatus('기기 임시 저장 공간이 부족해요. 서버 동기화를 확인해주세요.');}}
 function install(w:Workout){current.current=w;setWorkout(w);}
 function change(fn:(state:WorkoutState)=>WorkoutState){if(!current.current||current.current.status!=='active')return;const w={...current.current,state:fn(current.current.state)};install(w);keep(w);dirty.current=true;setStatus('기기에 임시 저장 · 서버 동기화 대기');if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>void flushRef.current(),1000);}
 async function flush():Promise<boolean>{
  if(blocked.current)return false;
  if(pending.current){await pending.current;if(blocked.current)return false;}
  const w=current.current;if(!w||!dirty.current||w.status!=='active')return true;
  const sent=JSON.stringify(w.state);
  const operation=(async()=>{try{const data=await request({action:'save',id:w.id,revision:w.revision,state:w.state});const newest=current.current;if(!newest||newest.id!==w.id)return true;install({...data.workout,state:newest.state});dirty.current=JSON.stringify(newest.state)!==sent;keep(current.current!);setStatus(dirty.current?'추가 변경 동기화 대기':'서버에 저장됨');setError('');return true;}catch(e){if((e as {status?:number}).status===409)blocked.current=true;setError((e as Error).message);setStatus('기기에 임시 저장됨 · 서버 저장 확인 필요');return false;}finally{pending.current=null;}})();
  pending.current=operation;const ok=await operation;if(ok&&dirty.current)return flush();return ok;
 }
 flushRef.current=flush;
 useEffect(()=>{const online=()=>void flushRef.current();window.addEventListener('online',online);return()=>{window.removeEventListener('online',online);if(timer.current)clearTimeout(timer.current);};},[]);
 useEffect(()=>{if(!open)return;const tick=()=>setRemaining(Math.max(0,Math.ceil((restUntil-Date.now())/1000)));tick();const t=setInterval(tick,500);return()=>clearInterval(t);},[open,restUntil]);
 async function begin(){setOpen(true);setBusy(true);setError('');setDiscard(false);blocked.current=false;try{
  const data=await request(sourceId?{action:'repeat',id:crypto.randomUUID(),sourceId}:{action:'start',id:crypto.randomUUID(),crewId,routineId:routine.id,kind,version:routine.version});let w=data.workout;
  try{const cached=JSON.parse(localStorage.getItem(storageKey)||'null') as Workout|null;if(cached?.id===w.id&&cached.user_id===userId&&cached.revision===w.revision&&cached.status==='active'){const parsed=workoutStateSchema.safeParse(cached.state);if(parsed.success&&JSON.stringify(parsed.data)!==JSON.stringify(w.state)){w={...w,state:parsed.data};dirty.current=true;}}else dirty.current=false;}catch{dirty.current=false;}
  install(w);setIndex(Math.max(0,w.state.exercises.findIndex(e=>e.sets.some(s=>!s.done))));setStatus(data.resumed?'진행 중인 운동을 이어서 열었어요.':sourceId?'지난 운동의 완료 값을 제안으로 불러왔어요. 모든 세트는 미완료로 시작해요.':data.carried?'이전 완료 기록을 제안값으로 불러왔어요. 실제 수행한 세트만 완료해주세요.':'루틴의 기본 횟수로 준비했어요. 중량과 RIR은 선택 입력이에요.');if(dirty.current)void flush();
 }catch(e){setError((e as Error).message);try{const cached=JSON.parse(localStorage.getItem(storageKey)||'null') as Workout|null;if(cached?.user_id===userId&&cached.status==='active'&&workoutStateSchema.safeParse(cached.state).success){install(cached);dirty.current=true;setStatus('오프라인 임시 기록을 열었어요. 연결되면 동기화해요.');}}catch{}}finally{setBusy(false);}}
 async function reload(){if(!current.current)return;setBusy(true);try{const r=await fetch(`/api/workouts?id=${encodeURIComponent(current.current.id)}`,{cache:'no-store'});const data=await r.json() as {workout:Workout;error?:string};if(!r.ok)throw Error(data.error);install(data.workout);setIndex(i=>Math.min(i,data.workout.state.exercises.length-1));dirty.current=false;blocked.current=false;keep(data.workout);setError('');setStatus('서버 기록으로 다시 열었어요.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function finish(action:'finish'|'discard'){setBusy(true);setError('');try{if(!await flush())return;const w=current.current;if(!w)return;const data=await request({action,id:w.id,revision:w.revision,...(action==='finish'?{state:w.state}:{})});install(data.workout);dirty.current=false;try{localStorage.removeItem(storageKey);}catch{}setStatus(action==='finish'?'운동 기록을 저장했어요. 출석과 미션 확인은 별도예요.':'이 운동 기록을 버렸어요.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const exercise=workout?.state.exercises[index];
 const updateExercise=(fn:(e:ExerciseLog)=>ExerciseLog)=>change(state=>({...state,exercises:state.exercises.map((e,i)=>i===index?fn(e):e)}));
 const updateSet=(id:string,patch:Partial<WorkoutSet>)=>updateExercise(e=>({...e,sets:e.sets.map(s=>s.id===id?{...s,...patch}:s)}));
 function complete(s:WorkoutSet){if(!exercise||!workout)return;if(!s.done&&(exercise.timed?s.seconds===null:s.reps===null)){setError('실제 횟수 또는 시간을 입력해주세요.');return;}updateSet(s.id,{done:!s.done});if(s.done)return;
  if(exercise.superset){const group=workout.state.exercises.map((e,i)=>({e,i})).filter(x=>x.e.superset===exercise.superset);const after=group.filter(x=>x.i>index).find(x=>x.e.sets.some(t=>!t.done));if(after){setIndex(after.i);setRestUntil(0);setStatus(`슈퍼세트 ${exercise.superset} · 다음 운동으로 이동했어요.`);return;}const next=group.find(x=>x.i<index&&x.e.sets.some(t=>!t.done));if(next)setIndex(next.i);}
  setRestUntil(Date.now()+(exercise.restSeconds??workout.state.restSeconds)*1000);
 }
 function addExercise(name:string,unit?:'seconds'|'reps'){if(!name.trim()||!workout||workout.state.exercises.length>=30)return;const guide=guideFor(name),equipment=guide?.equipment??'';const e:ExerciseLog={id:crypto.randomUUID(),name:name.trim().slice(0,60),plannedReps:10,timed:unit==='seconds',convention:equipment.includes('머신')||equipment.includes('케이블')?'machine':equipment.includes('덤벨')?'per_hand':equipment.includes('바벨')?'total':'unknown',equipmentLabel:'',prescription:'',sets:Array.from({length:3},()=>({id:crypto.randomUUID(),kind:'working',weight:null,reps:unit==='seconds'?null:10,seconds:unit==='seconds'?30:null,rir:null,done:false}))};change(state=>({...state,exercises:[...state.exercises,e]}));setIndex(workout.state.exercises.length);setCustomName('');}
 function moveExercise(delta:number){if(!workout)return;const target=index+delta;if(target<0||target>=workout.state.exercises.length)return;change(state=>{const list=[...state.exercises];[list[index],list[target]]=[list[target],list[index]];return {...state,exercises:list};});setIndex(target);}
 return <><button className="primary" onClick={()=>void begin()}>{sourceId?'이 운동 다시 하기':'운동 시작'}</button><Dialog open={open} onOpenChange={value=>{if(!busy){if(!value)void flush();setOpen(value);}}}><DialogContent className="app-dialog recorded-workout"><DialogTitle>{workout?.routine_name??routine.name}</DialogTitle><DialogDescription>본인만 보는 운동 기록 · 이전 값은 제안입니다. 실제 수행한 값으로 확인해주세요.</DialogDescription>
 {status&&<p className="training-save-status" role="status">{status}</p>}{error&&<div className="form-error" role="alert">{error}{blocked.current?<button className="secondary" disabled={busy} onClick={()=>void reload()}>기기 임시 변경 대신 서버 기록 불러오기</button>:<button className="text-button" disabled={busy} onClick={()=>void flush()}>동기화 다시 시도</button>}</div>}
 {busy&&!workout&&<p role="status">운동을 준비하는 중…</p>}
 {workout?.status==='active'&&exercise?<><div className="training-progress"><button className="secondary" disabled={busy||index===0} onClick={()=>setIndex(index-1)}>이전</button><span>{index+1} / {workout.state.exercises.length} 종목</span><button className="secondary" disabled={busy||index===workout.state.exercises.length-1} onClick={()=>setIndex(index+1)}>다음</button></div>
 <details><summary>운동 구성 변경 · 추가</summary><p className="muted">오늘 기록만 바뀌어요. 공통 루틴에는 영향을 주지 않아요.</p><div className="button-row"><button className="secondary" disabled={busy||index===0} onClick={()=>moveExercise(-1)}>현재 운동 앞으로</button><button className="secondary" disabled={busy||index===workout.state.exercises.length-1} onClick={()=>moveExercise(1)}>현재 운동 뒤로</button><button className="text-button" disabled={busy||workout.state.exercises.length<=1||exercise.sets.some(s=>s.done)} onClick={()=>{change(state=>({...state,exercises:state.exercises.filter(e=>e.id!==exercise.id)}));setIndex(Math.max(0,index-1));}}>미수행 운동 제거</button></div>{workout.state.exercises.length<30&&<><ExerciseLibrary onPick={addExercise}/><label className="field">직접 운동 이름 입력<input maxLength={60} value={customName} onChange={e=>setCustomName(e.target.value)}/></label><button className="secondary" disabled={busy||!customName.trim()} onClick={()=>addExercise(customName)}>직접 입력한 운동 추가</button></>}</details>
 <h3>{exercise.name}</h3><ExercisePreview exercises={[{id:exercise.id,name:exercise.name,sets:exercise.sets.length,reps:exercise.plannedReps,prescription:exercise.prescription,...(exercise.timed?{durationSeconds:exercise.sets[0]?.seconds??30}:{})}]}/>
 <details><summary>기록 기준 · 기구 설정</summary><label className="field">중량 기준<select disabled={busy} value={exercise.convention} onChange={e=>updateExercise(x=>({...x,convention:e.target.value as ExerciseLog['convention'],referenceMax:undefined}))}>{Object.entries(loadLabels).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label><label className="field">기구 구분 (다른 기구면 변경)<input disabled={busy} maxLength={60} value={exercise.equipmentLabel} placeholder="예: A 체스트프레스 · 좌석 3" onChange={e=>updateExercise(x=>({...x,equipmentLabel:e.target.value,referenceMax:undefined}))}/></label><label className="field">이 운동 휴식 (초, 비우면 공통 설정)<input disabled={busy} type="number" min={0} max={600} value={exercise.restSeconds??''} onChange={e=>updateExercise(x=>({...x,restSeconds:e.target.value===''?undefined:Number(e.target.value)}))}/></label><label className="field">슈퍼세트 그룹<select disabled={busy} value={exercise.superset??''} onChange={e=>updateExercise(x=>({...x,superset:e.target.value}))}><option value="">단독 운동</option>{['A','B','C','D'].map(v=><option key={v} value={v}>{v} 그룹</option>)}</select></label><p className="muted">같은 그룹의 운동을 차례로 완료한 뒤 휴식해요. 그룹 마지막 운동의 휴식 시간을 사용합니다.</p><label className="field">이 운동 메모<textarea disabled={busy} maxLength={500} value={exercise.note??''} onChange={e=>updateExercise(x=>({...x,note:e.target.value}))}/></label><p className="muted">RIR은 더 할 수 있었던 반복 수의 주관적 추정이에요. 모르면 비워두세요. RPE를 쓰면 일반적으로 RPE 10 ≈ RIR 0, RPE 8 ≈ RIR 2로 기록합니다. 이전 추정 1RM 대비 비율은 계산값이며 오늘의 실제 강도나 적정 중량을 보장하지 않아요.</p></details>
 <div className="training-set-list">{exercise.sets.map((s,i)=><div className={`training-set ${s.done?'done':''}`} key={s.id}><div className="training-set-heading"><strong>{i+1}세트</strong><button className="text-button" aria-label={`${i+1}세트 앞으로`} disabled={busy||i===0} onClick={()=>updateExercise(e=>{const sets=[...e.sets];[sets[i-1],sets[i]]=[sets[i],sets[i-1]];return {...e,sets};})}>↑</button><button className="text-button" aria-label={`${i+1}세트 뒤로`} disabled={busy||i===exercise.sets.length-1} onClick={()=>updateExercise(e=>{const sets=[...e.sets];[sets[i+1],sets[i]]=[sets[i],sets[i+1]];return {...e,sets};})}>↓</button><select aria-label={`${i+1}세트 종류`} disabled={busy} value={s.kind} onChange={e=>updateSet(s.id,{kind:e.target.value as WorkoutSet['kind']})}><option value="working">본세트</option><option value="warmup">웜업</option><option value="drop">드롭</option><option value="failure">실패</option></select></div>{exercise.referenceMax&&s.weight!==null&&<p className="muted">이전 추정 1RM 대비 {Math.round(s.weight/exercise.referenceMax.high*100)}–{Math.round(s.weight/exercise.referenceMax.low*100)}% · {new Date(exercise.referenceMax.date).toLocaleDateString('ko-KR',{timeZone:'Asia/Seoul'})} 기준</p>}<div className="training-set-inputs">{!exercise.timed&&<label>kg<input aria-label={`${i+1}세트 중량 kg`} type="number" inputMode="decimal" min={0} max={1500} step="any" disabled={busy} placeholder="선택" value={s.weight??''} onChange={e=>updateSet(s.id,{weight:e.target.value===''?null:Number(e.target.value)})}/></label>}<label>{exercise.timed?'초':'회'}<input aria-label={`${i+1}세트 ${exercise.timed?'시간 초':'횟수'}`} type="number" inputMode="numeric" min={1} max={exercise.timed?3600:100} disabled={busy} value={(exercise.timed?s.seconds:s.reps)??''} onChange={e=>updateSet(s.id,{[exercise.timed?'seconds':'reps']:e.target.value===''?null:Number(e.target.value)})}/></label>{!exercise.timed&&<label>RIR<input aria-label={`${i+1}세트 여유 반복 수`} type="number" inputMode="numeric" min={0} max={10} disabled={busy} placeholder="선택" value={s.rir??''} onChange={e=>updateSet(s.id,{rir:e.target.value===''?null:Number(e.target.value)})}/></label>}<button className={s.done?'secondary':'primary'} aria-label={`${i+1}세트 ${s.done?'완료 취소':'완료'}`} aria-pressed={s.done} disabled={busy} onClick={()=>complete(s)}>{s.done?'완료됨':'완료'}</button></div></div>)}</div>
 <div className="button-row"><button className="secondary" disabled={busy||exercise.sets.length>=30} onClick={()=>updateExercise(e=>({...e,sets:[...e.sets,{...e.sets.at(-1)!,id:crypto.randomUUID(),done:false,rir:null}]}))}>이전 값으로 세트 추가</button><button className="text-button" disabled={busy||exercise.sets.length<=1||exercise.sets.at(-1)?.done} onClick={()=>updateExercise(e=>({...e,sets:e.sets.slice(0,-1)}))}>마지막 미완료 세트 제거</button></div>
 {remaining>0&&<div className="training-rest" role="timer">휴식 {Math.floor(remaining/60)}:{String(remaining%60).padStart(2,'0')}<button className="text-button" onClick={()=>setRestUntil(0)}>휴식 끝내기</button></div>}
 <details><summary>운동 마무리 · 컨디션</summary><label className="field">설정 휴식<select disabled={busy} value={workout.state.restSeconds} onChange={e=>change(s=>({...s,restSeconds:Number(e.target.value)}))}>{[30,60,90,120,180,300].map(n=><option key={n} value={n}>{n}초</option>)}</select></label><label className="field">운동 중 불편감<select disabled={busy} value={workout.state.discomfort} onChange={e=>change(s=>({...s,discomfort:e.target.value as WorkoutState['discomfort']}))}><option value="unreported">아직 확인하지 않음</option><option value="none">없었어요</option><option value="yes">있었어요</option></select></label><label className="check-row"><input type="checkbox" disabled={busy} checked={workout.state.conditionsConfirmed} onChange={e=>change(s=>({...s,conditionsConfirmed:e.target.checked}))}/>기구·중량 기준·가동범위·휴식을 이전 기록과 같은 조건으로 맞췄어요</label><label className="field">실제 운동 시간 분 (선택)<input disabled={busy} type="number" min={1} max={1440} value={workout.state.durationMinutes??''} onChange={e=>change(s=>({...s,durationMinutes:e.target.value===''?undefined:Number(e.target.value)}))}/></label><label className="field">운동 메모<textarea disabled={busy} rows={3} maxLength={2000} value={workout.state.note} onChange={e=>change(s=>({...s,note:e.target.value}))}/></label><label className="check-row"><input type="checkbox" checked={discard} onChange={e=>setDiscard(e.target.checked)}/>이 운동 기록을 버리기</label>{discard&&<button className="danger" disabled={busy} onClick={()=>void finish('discard')}>버리기 확정</button>}</details>
 <button className="primary full-width" disabled={busy} onClick={()=>void finish('finish')}>{busy?'저장 중…':'운동 종료 · 완료한 세트 저장'}</button><p className="muted">닫으면 나중에 이어서 할 수 있어요. 기록 입력 없이 세트 완료만 사용해도 됩니다.</p>
 </>:workout?.status==='completed'?<div className="training-summary"><strong>완료한 본세트 {workoutTotals(workout).sets}개</strong><p>기록한 중량 × 횟수 합계 {workoutTotals(workout).volume.toLocaleString()} kg·회</p><p>시간 운동 {workoutTotals(workout).timedSeconds}초</p><p className="muted">웜업은 합계에서 제외됩니다. 이 합계는 실제 근육 부하나 칼로리가 아닙니다.</p></div>:null}
 </DialogContent></Dialog></>;
}
