'use client';
import {useState} from 'react';
import {TrainingRecordEditor} from './training-record-editor';
import {TrainingTrends} from './training-trends';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import type {analyzeTraining} from '@/lib/training-analysis';
import {loadLabels,type TrainingProfile,type Workout} from '@/lib/training-model';
import './training.css';
type Summary={cursor:string|null;active:Workout|null;profile:TrainingProfile|null;history:{id:string;name:string;date:number;sets:number;volume:number;missingWeights:number}[];analysis:ReturnType<typeof analyzeTraining>;truncated:boolean};
export function TrainingHistory({userId}:{userId?:string}){
 const [open,setOpen]=useState(false),[data,setData]=useState<Summary|null>(null),[detail,setDetail]=useState<Workout|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [editing,setEditing]=useState(false);
 const [profile,setProfile]=useState<TrainingProfile>({goal:'hypertrophy',experience:'beginner',daysPerWeek:3,adult:false});
 async function load(){if(!userId)return;setBusy(true);setError('');try{const r=await fetch('/api/workouts',{cache:'no-store'});const result=await r.json() as Summary&{error?:string};if(!r.ok)throw Error(result.error);setData(result);if(result.profile)setProfile(result.profile);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function saveProfile(){setBusy(true);setError('');try{const r=await fetch('/api/workouts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'profile',profile})});const result=await r.json() as {error?:string};if(!r.ok)throw Error(result.error);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function show(id:string){setBusy(true);setError('');try{const r=await fetch(`/api/workouts?id=${encodeURIComponent(id)}`,{cache:'no-store'});const result=await r.json() as {workout:Workout;error?:string};if(!r.ok)throw Error(result.error);setDetail(result.workout);setEditing(false);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function more(){if(!data?.cursor)return;setBusy(true);setError('');try{const r=await fetch('/api/workouts?history=1&cursor='+encodeURIComponent(data.cursor),{cache:'no-store'});const result=await r.json() as Pick<Summary,'history'|'cursor'>&{error?:string};if(!r.ok)throw Error(result.error);setData(current=>current?{...current,history:[...current.history,...result.history.filter(item=>!current.history.some(old=>old.id===item.id))],cursor:result.cursor}:current);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function correct(workout:Workout){setBusy(true);setError('');try{const r=await fetch('/api/workouts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'correct',id:workout.id,revision:workout.revision,state:workout.state})});const result=await r.json() as {workout:Workout;error?:string};if(!r.ok)throw Error(result.error);setDetail(result.workout);setEditing(false);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <><button className="secondary" aria-label="내 운동 기록·분석" onClick={()=>{setOpen(true);setDetail(null);setEditing(false);void load();}}>기록·분석</button><Dialog open={open} onOpenChange={value=>{if(!busy)setOpen(value);}}><DialogContent className="app-dialog training-history"><DialogTitle>{detail?detail.routine_name:'내 운동 기록·분석'}</DialogTitle><DialogDescription>본인만 볼 수 있어요. 기록에 없는 수행·피로·회복 상태를 추측하지 않습니다.</DialogDescription>
 {!userId?<a className="primary" href="/login?returnTo=%2F">로그인하고 기록하기</a>:<>
 {error&&<p role="alert" className="form-error">{error}</p>}{busy&&<p role="status">불러오는 중…</p>}
 {detail&&editing?<TrainingRecordEditor key={detail.id+':'+detail.revision} workout={detail} busy={busy} onSave={correct} onCancel={()=>setEditing(false)}/>:detail?<><button className="text-button" onClick={()=>setDetail(null)}>← 기록 목록</button><p>{new Date(detail.finished_at??detail.started_at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})}</p>{detail.state.exercises.map(e=><section key={e.id}><h3>{e.name}</h3><p className="muted">{loadLabels[e.convention]} {e.equipmentLabel?`· ${e.equipmentLabel}`:''}</p>{e.sets.filter(s=>s.done).map((s,i)=><p key={s.id}>{i+1}. {s.kind==='warmup'?'웜업':s.kind==='drop'?'드롭':'본세트'} · {e.timed?`${s.seconds}초`:`${s.weight??'미입력'}kg × ${s.reps}회`} {s.rir!==null?`· RIR ${s.rir}`:''}</p>)}</section>)}{detail.state.note&&<p>{detail.state.note}</p>}<button className="secondary" disabled={busy} onClick={()=>setEditing(true)}>이 기록 수정</button></>:data&&<>
 {data.active&&<div className="training-active"><strong>진행 중: {data.active.routine_name}</strong><p>루틴의 ‘운동 시작’을 누르면 진행 중인 기록을 이어서 열어요.</p></div>}
 <div className="training-metrics"><div><strong>{data.analysis.sessions}</strong><span>최근 90일 운동</span></div><div><strong>{data.analysis.trainingDays}</strong><span>운동한 날짜</span></div><div><strong>{data.analysis.sets}</strong><span>완료 본세트·드롭세트</span></div></div>
 {data.truncated&&<p className="muted">기록이 많아 최근 200회까지 분석합니다.</p>}
 <details open={!data.profile}><summary>코칭 기준 설정</summary><div className="form-stack"><label className="field">목표<select value={profile.goal} onChange={e=>setProfile({...profile,goal:e.target.value as TrainingProfile['goal']})}><option value="hypertrophy">근육 성장</option><option value="strength">근력 향상</option><option value="consistency">꾸준한 운동</option></select></label><label className="field">운동 경력<select value={profile.experience} onChange={e=>setProfile({...profile,experience:e.target.value as TrainingProfile['experience']})}><option value="beginner">입문 · 기본 동작을 배우는 중</option><option value="intermediate">꾸준히 훈련 중</option><option value="advanced">숙련자</option></select></label><label className="field">주간 목표 운동일<input type="number" min={1} max={7} value={profile.daysPerWeek} onChange={e=>setProfile({...profile,daysPerWeek:Number(e.target.value)})}/></label><label className="check-row"><input type="checkbox" checked={profile.adult} onChange={e=>setProfile({...profile,adult:e.target.checked})}/>성인용 훈련 지침의 적용 대상입니다</label><button className="primary" disabled={busy} onClick={()=>void saveProfile()}>설정 저장</button></div></details>
 <p className="muted">최근 7일 {data.analysis.last7Days}일 운동{data.analysis.weeklyTarget?` · 주간 목표 ${data.analysis.weeklyTarget}일`:" · 목표 미설정"}</p><section><h3>최근 12주 · 7일 단위 운동 횟수</h3><div className="training-week-chart">{data.analysis.weekly.map(w=><div key={w.label} title={`${w.label}부터 7일: ${w.sessions}회, ${w.sets}세트`}><span>{w.sessions}</span><i style={{height:Math.max(3,w.sessions/Math.max(1,...data.analysis.weekly.map(x=>x.sessions))*70)}}/><small>{w.label.slice(5)}</small></div>)}</div></section>
 <details><summary>운동별 변화 비교</summary><TrainingTrends trends={data.analysis.trends}/></details><details><summary>운동별 검토 가이드 ({data.analysis.advice.length})</summary><p className="muted">서로 다른 날짜의 기록 3회, 최근 14일 내 기록, 최근 2회의 목표 달성 여부는 SPOT의 검토 기준입니다. 개인별 정확도가 검증된 처방은 아닙니다. RIR·불편감은 본인 보고에 의존합니다.</p>{data.analysis.advice.length?data.analysis.advice.map((a,i)=><section key={i} className="training-advice"><h3>{a.exercise}</h3><strong>{a.title}</strong><ul>{a.reasons.map(r=><li key={r}>{r}</li>)}</ul>{a.missing.length>0&&<p>추가 확인: {a.missing.join(' · ')}</p>}</section>):<p>운동을 완료하면 기록에 근거한 검토 항목을 보여드려요.</p>}{data.analysis.sources.map(s=><a className="text-button" key={s.url} href={s.url} target="_blank" rel="noopener noreferrer">{s.title} ↗</a>)}</details>
 <section><h3>운동 기록</h3><p className="muted">기간 제한 없이 최신순으로 찾아볼 수 있어요.</p>{data.history.length?data.history.map(w=><button className="training-history-row" key={w.id} disabled={busy} onClick={()=>void show(w.id)}><strong>{w.name}</strong><small>{new Date(w.date).toLocaleDateString('ko-KR',{timeZone:'Asia/Seoul'})} · {w.sets}세트 · 입력 중량 합계 {w.volume.toLocaleString()}kg·회</small></button>):<p className="muted">아직 완료한 운동 기록이 없어요.</p>}{data.cursor&&<button className="secondary full-width" disabled={busy} onClick={()=>void more()}>이전 기록 더 보기</button>}</section><p className="muted">중량 합계는 입력 기준으로 계산하며 근육 부하·칼로리가 아닙니다. 다른 기구·총중량/한쪽 중량 기록은 비교하지 마세요.</p>
 </>}
 </>}
 </DialogContent></Dialog></>;
}
