 'use client';
import {useState} from 'react';
import type {Question} from '@/lib/training-community';
export function TrainingCommunity({userId}:{userId?:string}){
 const [open,setOpen]=useState(false),[items,setItems]=useState<Question[]>([]),[parent,setParent]=useState<Question|null>(null),[cursor,setCursor]=useState<string|null>(null),[admin,setAdmin]=useState(false),[body,setBody]=useState(''),[confirmed,setConfirmed]=useState(false),[editing,setEditing]=useState<Question|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 async function load(question:Question|null=parent,more=false){setBusy(true);setError('');try{const params=new URLSearchParams();if(question)params.set('parent',question.id);if(more&&cursor)params.set('cursor',cursor);const r=await fetch('/api/training-community?'+params,{cache:'no-store'});const d=await r.json() as {items:Question[];cursor:string|null;admin:boolean;error?:string};if(!r.ok)throw Error(d.error);setItems(old=>more?[...old,...d.items.filter(e=>!old.some(x=>x.id===e.id))]:d.items);setAdmin(d.admin);setCursor(d.cursor);setParent(question);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function act(payload:unknown){setBusy(true);setError('');try{const r=await fetch('/api/training-community',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);return true;}catch(e){setError((e as Error).message);return false;}finally{setBusy(false);}}
 return <details className="panel" open={open} onToggle={e=>{const value=e.currentTarget.open;setOpen(value);if(value&&userId)void load(null);}}><summary>운동 Q&A · SPOT 친구들에게 물어보기</summary>{!userId?<a href="/login?returnTo=%2F" className="secondary">로그인하고 참여하기</a>:<div className="form-stack"><p className="muted">작성한 이름과 글은 모든 SPOT 로그인 회원에게 공개됩니다. 개인 신체·식단 기록은 자동으로 공유되지 않아요. 친구의 경험은 전문 진단이나 처방이 아닙니다.</p>{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}{parent&&<><button className="text-button" onClick={()=>{setEditing(null);setBody('');void load(null);}}>← 질문 목록</button><h3>{parent.author_name}의 질문</h3><p>{parent.body}</p></>}
 <form onSubmit={async e=>{e.preventDefault();const ok=await act(editing?{action:'edit',id:editing.id,revision:editing.revision,body}:{action:'post',id:crypto.randomUUID(),parent:parent?.id??null,body,publishConfirmed:confirmed});if(ok){setBody('');setEditing(null);setConfirmed(false);await load();}}}><label className="field">{editing?'글 수정':parent?'답변 작성':'질문 작성'}<textarea required minLength={5} maxLength={2000} rows={3} value={body} onChange={e=>setBody(e.target.value)}/></label>{!editing&&<label className="check-row"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>전체 SPOT 회원에게 공개되는 글입니다</label>}<div className="button-row"><button className="primary" disabled={busy||(!editing&&!confirmed)} type="submit">{editing?'수정 저장':'게시하기'}</button>{editing&&<button className="secondary" type="button" onClick={()=>{setEditing(null);setBody('');}}>취소</button>}</div></form>
 {items.map(q=><article className="training-advice" key={q.id}><strong>{q.author_name}</strong><small> · {new Date(q.created_at).toLocaleDateString('ko-KR',{timeZone:'Asia/Seoul'})}</small><p style={{whiteSpace:'pre-wrap'}}>{q.body}</p>{admin&&q.reports>0&&<p>신고 {q.reports}건</p>}<div className="button-row">{!parent&&<button className="secondary" disabled={busy} onClick={()=>{setBody('');setEditing(null);void load(q);}}>답변 보기</button>}{q.mine&&<button className="text-button" disabled={busy} onClick={()=>{setEditing(q);setBody(q.body);}}>수정</button>}{(q.mine||admin)&&<button className="text-button" disabled={busy} onClick={async()=>{if(await act({action:'hide',id:q.id,revision:q.revision}))await load();}}>글 숨기기</button>}<button className="text-button" disabled={busy} onClick={async()=>{if(await act({action:'report',id:q.id}))setMessage('관리자가 확인할 수 있도록 신고했어요.');}}>신고</button></div></article>)}{!items.length&&!busy&&<p>아직 {parent?'답변':'질문'}이 없어요.</p>}{cursor&&<button className="secondary" disabled={busy} onClick={()=>void load(parent,true)}>이전 글 더 보기</button>}
 </div>}</details>;
}
