 'use client';
import {useEffect,useState} from 'react';
import {intervalState,platePlan} from '@/lib/training-insights';
import {backupBatch} from '@/lib/training-backup-model';
import type {TrainingProfile,Workout} from '@/lib/training-model';
import type {JournalEntry} from '@/lib/training-journal';
function download(name:string,data:string,type:string){const url=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function TrainingTools({profile,onRestored,userId}:{userId:string;profile:TrainingProfile|null;onRestored:()=>void}){
 const [work,setWork]=useState(30),[rest,setRest]=useState(15),[rounds,setRounds]=useState(8),[start,setStart]=useState<number|null>(null),[now,setNow]=useState(Date.now()),[paused,setPaused]=useState<number|null>(null);
 const [target,setTarget]=useState(60),[bar,setBar]=useState(20),[plates,setPlates]=useState([25,20,15,10,5,2.5,1.25].map(weight=>({weight,pairs:2}))),[plateResult,setPlateResult]=useState('');
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('spot-plate-settings:'+userId)||'null');if(saved&&Array.isArray(saved.plates)){platePlan(saved.bar,saved.bar,saved.plates);setBar(saved.bar);setPlates(saved.plates);}}catch{}},[userId]);
 const [busy,setBusy]=useState(false),[status,setStatus]=useState(''),[error,setError]=useState(''),[backup,setBackup]=useState<{format:'spot-training-v1';workouts:Workout[];journal:JournalEntry[];profile:TrainingProfile|null}|null>(null);
 useEffect(()=>{if(start===null||paused!==null)return;const t=setInterval(()=>setNow(Date.now()),250);return()=>clearInterval(t);},[start,paused]);
 const clock=start!==null?intervalState(start,paused??now,work,rest,rounds):null;
 async function exportFile(csv=false){setBusy(true);setError('');setStatus('기록을 모으는 중…');try{const workouts:Workout[]=[],journal:JournalEntry[]=[];let cursor:string|null=null;do{const r:Response=await fetch('/api/training-backup'+(cursor?'?cursor='+encodeURIComponent(cursor):''),{cache:'no-store'});const d=await r.json() as {workouts:Workout[];cursor:string|null;error?:string};if(!r.ok)throw Error(d.error);workouts.push(...d.workouts);cursor=d.cursor;}while(cursor);do{const r=await fetch('/api/journal'+(cursor?'?cursor='+encodeURIComponent(cursor):''),{cache:'no-store'});const d=await r.json() as {entries:JournalEntry[];cursor:string|null;error?:string};if(!r.ok)throw Error(d.error);journal.push(...d.entries);cursor=d.cursor;}while(cursor);
 if(csv){const cell=(v:unknown)=>'"'+String(v??'').replace(/^[\s]*[=+@-]/,"'").replaceAll('"','""')+'"';const rows=[['date','routine','exercise','set_type','weight_kg','reps','seconds','rir','weight_basis','equipment']];for(const w of workouts)for(const e of w.state.exercises)for(const s of e.sets)if(s.done)rows.push([new Date(w.finished_at!).toISOString(),w.routine_name,e.name,s.kind,String(s.weight??''),String(s.reps??''),String(s.seconds??''),String(s.rir??''),e.convention,e.equipmentLabel]);download('spot-workouts.csv','\uFEFF'+rows.map(r=>r.map(cell).join(',')).join('\r\n'),'text/csv;charset=utf-8');}
 else download('spot-training-backup.json',JSON.stringify({format:'spot-training-v1',workouts,journal,profile},null,2),'application/json');setStatus(`완료 운동 ${workouts.length}회 · 생활 기록 ${journal.length}건을 내보냈어요.`);
 }catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function restore(){if(!backup)return;setBusy(true);setError('');let added=0,skipped=0;try{for(let i=0;i<Math.max(backup.workouts.length,backup.journal.length,1);i+=3){const r:Response=await fetch('/api/training-backup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...backup,workouts:backup.workouts.slice(i,i+3),journal:backup.journal.slice(i,i+3)})});const d=await r.json() as {added:number;skipped:number;error?:string};if(!r.ok)throw Error(d.error);added+=d.added;skipped+=d.skipped;setStatus(`${added}건 복원 · 기존 ${skipped}건 유지`);}setBackup(null);onRestored();}catch(e){setError(`${added}건 복원 후 중단: ${(e as Error).message}. 같은 파일로 재시도하면 기존 ID는 건너뜁니다.`);}finally{setBusy(false);}}
 return <div className="form-stack"><details><summary>인터벌 타이머</summary><p className="muted">화면이 열려 있을 때 확인하세요. 앱이 잠들면 소리·진동을 보장하지 않아요.</p><div className="journal-fields">{[[work,setWork,'운동 초',1,3600],[rest,setRest,'휴식 초',0,600],[rounds,setRounds,'라운드',1,100]].map(([v,set,label,min,max])=><label className="field" key={String(label)}>{String(label)}<input disabled={start!==null} type="number" min={Number(min)} max={Number(max)} value={Number(v)} onChange={e=>(set as (v:number)=>void)(Number(e.target.value))}/></label>)}</div>{clock&&<div className="training-rest" role="timer">{clock.phase==='done'?'인터벌 완료':`${clock.round}/${rounds} · ${clock.phase==='work'?'운동':'휴식'} ${clock.remaining}초`}{paused!==null&&' · 일시정지'}</div>}<div className="button-row">{start===null?<button className="primary" onClick={()=>{if(!Number.isInteger(work)||work<1||work>3600||!Number.isInteger(rest)||rest<0||rest>600||!Number.isInteger(rounds)||rounds<1||rounds>100){setError('타이머 입력 범위를 확인해주세요.');return;}setStart(Date.now());setNow(Date.now());setError('');}}>타이머 시작</button>:<><button className="secondary" onClick={()=>{if(paused!==null){setStart(start+Date.now()-paused);setNow(Date.now());setPaused(null);}else setPaused(Date.now());}}>{paused!==null?'계속':'일시정지'}</button><button className="secondary" onClick={()=>{setStart(null);setPaused(null);}}>초기화</button></>}</div></details>
 <details><summary>바벨 원판 계산기</summary><div className="journal-fields"><label className="field">목표 총 중량 kg<input type="number" step="any" value={target} onChange={e=>setTarget(Number(e.target.value))}/></label><label className="field">바벨 자체 중량 kg<input type="number" min={0} step="any" value={bar} onChange={e=>setBar(Number(e.target.value))}/></label></div><p className="muted">보유한 원판 쌍 수를 설정하세요. 양쪽에 같은 무게로 계산합니다.</p><div className="journal-fields">{plates.map((p,i)=><label className="field" key={p.weight}>{p.weight}kg 원판 · 쌍 수<input type="number" min={0} max={20} value={p.pairs} onChange={e=>setPlates(plates.map((x,j)=>j===i?{...x,pairs:Number(e.target.value)}:x))}/></label>)}</div><button className="secondary" onClick={()=>{try{const p=platePlan(target,bar,plates);try{localStorage.setItem('spot-plate-settings:'+userId,JSON.stringify({bar,plates}));}catch{}setPlateResult(`${p.actual}kg ${p.exact?'정확히 구성':'가장 가까운 낮은 중량'} · 한쪽: ${p.side.map(x=>`${x.weight}kg × ${x.count}장`).join(' + ')||'빈 바'}`);}catch(e){setPlateResult((e as Error).message);}}}>원판 계산</button>{plateResult&&<p role="status">{plateResult}</p>}</details>
 <details><summary>기록 백업 · 복원</summary><p className="muted">완료 운동과 생활 기록을 내 계정용 파일로 저장해요. 진행 중 운동·크루 공통 데이터는 포함하지 않아요. 신체·식단 정보가 담긴 파일은 안전하게 보관하세요.</p><div className="button-row"><button className="secondary" disabled={busy} onClick={()=>void exportFile()}>JSON 백업 다운로드</button><button className="secondary" disabled={busy} onClick={()=>void exportFile(true)}>운동 CSV 다운로드</button></div><label className="field">SPOT 백업 파일 선택<input type="file" accept=".json,application/json" disabled={busy} onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;setError('');setBackup(null);try{if(file.size>30*1024*1024)throw Error('30MB 이하 파일을 선택해주세요.');const b=JSON.parse(await file.text());if(!Array.isArray(b.workouts)||!Array.isArray(b.journal)||b.workouts.length>10000||b.journal.length>10000)throw Error('백업 형식을 확인해주세요.');for(let i=0;i<Math.max(b.workouts.length,b.journal.length,1);i+=3)backupBatch.parse({...b,workouts:b.workouts.slice(i,i+3),journal:b.journal.slice(i,i+3)});setBackup(b);}catch{setError('유효한 SPOT 백업 파일인지 확인해주세요.');}}}/></label>{backup&&<div><p>운동 {backup.workouts.length}회 · 생활 {backup.journal.length}건. 같은 ID의 기존 기록과 코칭 설정은 덮어쓰지 않아요.</p><button className="primary" disabled={busy} onClick={()=>void restore()}>내 계정에 복원</button></div>}</details>
 {status&&<p role="status">{status}</p>}{error&&<p role="alert">{error}</p>}
 </div>;
}
