'use client';
import {useEffect,useState} from 'react';
import {RecordedWorkout} from './training-workout';
import type {Routine,Exercise} from '@/lib/gym-model';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {ExercisePreview} from './exercise-guide';
import {exerciseGuides,guideFor} from '@/lib/exercise-guides';
function QuickWorkoutRunner({routine}:{routine:Routine}){const [open,setOpen]=useState(false),[index,setIndex]=useState(0),[sets,setSets]=useState(0),[rest,setRest]=useState(60),[until,setUntil]=useState(0),[remaining,setRemaining]=useState(0),[choice,setChoice]=useState<Exercise|null>(null);const exercise=choice??routine.exercises[index];useEffect(()=>{if(!open)return;const tick=()=>setRemaining(Math.max(0,Math.ceil((until-Date.now())/1000)));tick();const t=setInterval(tick,500);return()=>clearInterval(t);},[open,until]);const guide=exercise&&guideFor(exercise.name),alternatives=guide?exerciseGuides.filter(g=>g.body===guide.body&&g.id!==guide.id&&(g.unit==='seconds')===(exercise.durationSeconds!==undefined)):[];function next(){setIndex(i=>i+1);setSets(0);setUntil(0);setChoice(null);}return <><button className="primary" onClick={()=>{setIndex(0);setSets(0);setChoice(null);setUntil(0);setOpen(true);}}>운동 시작</button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="app-dialog workout-runner"><DialogTitle>{index>=routine.exercises.length?'오늘 운동을 마쳤어요':routine.name}</DialogTitle><DialogDescription>무게 기록 없이 한 종목씩 따라가요. 진행 체크는 이 화면에서만 사용하며 출석은 별도로 확인합니다.</DialogDescription>{index<routine.exercises.length&&exercise?<><p className="muted">{index+1} / {routine.exercises.length} 종목</p><h2>{exercise.name}</h2><ExercisePreview exercises={[exercise]}/><p>{sets} / {exercise.sets}세트 완료 · 기준 {exercise.durationSeconds!==undefined?`${exercise.durationSeconds}초`:`${exercise.reps}회`}</p>{exercise.prescription&&<details><summary>자세한 세트 구성</summary><p>{exercise.prescription}</p></details>}<div className="rest-clock" role="timer" aria-label="남은 휴식 시간">{remaining?`${Math.floor(remaining/60)}:${String(remaining%60).padStart(2,'0')}`:'준비되면 시작'}</div><label className="field">세트 사이 휴식<select value={rest} onChange={e=>setRest(Number(e.target.value))}>{[30,60,90,120,180].map(n=><option key={n} value={n}>{n}초</option>)}</select></label><div className="button-row"><button className="primary" disabled={sets>=exercise.sets} onClick={()=>{setSets(n=>n+1);setUntil(Date.now()+rest*1000);}}>세트 완료 · 휴식</button>{remaining>0&&<button className="secondary" onClick={()=>setUntil(0)}>휴식 끝내기</button>}<button className="secondary" onClick={next}>다음 종목</button></div>{alternatives.length>0&&<details><summary>기구가 없나요? 대체 운동 보기</summary><p className="muted">같은 부위의 후보입니다. 기구·자세가 다르므로 가이드를 확인하고 선택하세요.</p><div className="button-row">{alternatives.map(g=><button className="secondary" key={g.id} onClick={()=>{setChoice({...exercise,name:g.name,prescription:''});setSets(0);setUntil(0);}}>{g.name}</button>)}</div></details>}</>:<p>수고했어요. ‘미션’ 탭에서 해당 일정의 출석을 체크하고 친구에게 확인받으세요.</p>}</DialogContent></Dialog></>;}
export const beginnerTemplates:Omit<Routine,'id'|'version'>[]=[{name:'입문 전신 A',subtitle:'머신 중심 · 기본 동작 익히기',notes:'입문용 구성 예시입니다. 가벼운 무게로 기구 조절과 동작을 먼저 익히세요. 반복 수보다 자세를 우선하고 트레이너와 본인에게 맞게 조절하세요.',exercises:[{id:'chest',name:'체스트 프레스',sets:2,reps:10},{id:'row',name:'시티드 케이블 로우',sets:2,reps:10},{id:'legpress',name:'레그 프레스',sets:2,reps:10},{id:'curl',name:'레그 컬',sets:2,reps:10},{id:'core',name:'크런치',sets:2,reps:10}]},{name:'입문 전신 B',subtitle:'당기기 · 하체 · 어깨 기본',notes:'입문용 구성 예시입니다. 기구 사용법을 확인하고 조절 가능한 무게로 시작하세요. 기존 루틴과 번갈아 쓰거나 트레이너와 조정할 수 있어요.',exercises:[{id:'lat',name:'랫 풀다운',sets:2,reps:10},{id:'legs',name:'레그 익스텐션',sets:2,reps:10},{id:'shoulder',name:'숄더 프레스',sets:2,reps:10},{id:'biceps',name:'덤벨 컬',sets:2,reps:10}]}];

export function WorkoutRunner({routine,userId,crewId,kind="common"}:{routine:Routine;userId?:string;crewId?:string;kind?:"common"|"personal"}){return userId&&crewId?<RecordedWorkout routine={routine} userId={userId} crewId={crewId} kind={kind}/>:<QuickWorkoutRunner routine={routine}/>;}
