export type Pose='bench'|'incline'|'overhead'|'press'|'row'|'pull'|'raise'|'curl'|'extend'|'squat'|'hinge'|'legpress'|'legcurl'|'legextend'|'core'|'fly'|'dip'|'shrug';
export type ExerciseGuide={id:string;name:string;body:string;equipment:string;pose:Pose;match:string[];start:string;finish:string;cues:string[]};
export const exerciseGuides:ExerciseGuide[]=[
 {id:'incline',name:'인클라인 덤벨 프레스',body:'가슴',equipment:'덤벨 · 벤치',pose:'incline',match:['인클라인 덤벨프레스','인클라인 덤벨 프레스'],start:'등과 엉덩이를 벤치에 대고 덤벨을 가슴 옆에 준비해요.',finish:'손목을 곧게 유지하면서 덤벨을 위로 밀고 천천히 돌아와요.',cues:['발바닥을 바닥에 고정해요.','허리를 과하게 꺾지 않아요.','혼자 실패 지점까지 무리하지 않아요.']},
 {id:'bench',name:'벤치프레스',body:'가슴',equipment:'바벨 · 벤치',pose:'bench',match:['벤치프레스','벤치 프레스'],start:'발을 바닥에 두고 벤치에 누워 바를 잡아요.',finish:'가슴 쪽으로 조절하며 내린 뒤 밀어 올려요.',cues:['세이프티 바 또는 보조자를 준비해요.','손목과 팔꿈치를 안정적으로 맞춰요.','가슴에서 반동을 주지 않아요.']},
 {id:'chest',name:'체스트 프레스',body:'가슴',equipment:'머신',pose:'press',match:['체스트 프레스'],start:'손잡이가 가슴 높이에 오도록 의자를 맞춰요.',finish:'등을 패드에 붙이고 손잡이를 앞으로 밀어요.',cues:['어깨를 으쓱하지 않아요.','팔꿈치를 세게 잠그지 않아요.','무게추가 부딪히지 않게 돌아와요.']},
 {id:'fly',name:'펙덱 · 체스트 플라이',body:'가슴',equipment:'머신 · 케이블',pose:'fly',match:['펙덱','체스트 플라이'],start:'가슴 높이에서 양팔을 편안하게 벌려요.',finish:'팔꿈치 각도를 유지하며 가슴 앞쪽으로 모아요.',cues:['어깨 뒤로 과하게 벌리지 않아요.','손보다 위팔이 모인다고 생각해요.','통증 없는 범위에서 천천히 해요.']},
 {id:'dip',name:'딥스',body:'삼두 · 가슴',equipment:'평행봉 · 보조 머신',pose:'dip',match:['딥스','딥 머신'],start:'손잡이를 잡고 어깨가 귀에서 멀어지도록 몸을 지지해요.',finish:'팔꿈치를 굽혀 내려갔다가 팔로 밀어 올라와요.',cues:['초보자는 보조 머신을 활용해요.','어깨 앞쪽이 아프면 깊이를 줄여요.','흔들거나 반동을 주지 않아요.']},
 {id:'row',name:'로우',body:'등',equipment:'머신 · 케이블 · 덤벨',pose:'row',match:['로우','덤벨 로우'],start:'상체를 안정시키고 팔을 앞으로 뻗어 손잡이를 잡아요.',finish:'팔꿈치를 몸통 뒤쪽으로 보내며 당겼다가 천천히 뻗어요.',cues:['허리로 반동을 만들지 않아요.','어깨를 과하게 으쓱하지 않아요.','가슴 지지형은 가슴을 패드에 붙여요.']},
 {id:'pulldown',name:'랫 풀다운',body:'등',equipment:'케이블 머신',pose:'pull',match:['랫풀다운','랫 풀다운'],start:'허벅지 패드를 고정하고 위쪽 손잡이를 잡아요.',finish:'팔꿈치를 아래로 내리며 가슴 위쪽 방향으로 당겨요.',cues:['목 뒤로 바를 내리지 않아요.','몸을 크게 젖히지 않아요.','복귀할 때도 무게를 제어해요.']},
 {id:'straight',name:'스트레이트 암 풀다운',body:'등',equipment:'케이블',pose:'extend',match:['스트레이트 암'],start:'팔꿈치를 살짝 굽힌 채 손잡이를 앞·위쪽에 둬요.',finish:'팔꿈치 각도를 유지하며 손잡이를 허벅지 쪽으로 내려요.',cues:['팔꿈치를 굽혀 로우처럼 당기지 않아요.','복부에 힘을 주고 허리를 고정해요.','어깨 가동 범위 안에서 돌아와요.']},
 {id:'shoulder',name:'숄더 프레스',body:'어깨',equipment:'덤벨 · 스미스 · 머신',pose:'overhead',match:['숄더프레스','숄더 프레스'],start:'손잡이 또는 덤벨을 어깨 옆에 두고 몸통을 세워요.',finish:'머리 위로 밀어 올린 뒤 어깨 높이로 내려요.',cues:['등받이에 등을 안정적으로 지지해요.','허리를 꺾어 밀지 않아요.','가벼운 무게로 편한 궤적을 찾아요.']},
 {id:'lateral',name:'사이드 레터럴 레이즈',body:'어깨',equipment:'덤벨',pose:'raise',match:['레터럴','사이드 레이즈'],start:'팔꿈치를 조금 굽히고 덤벨을 몸 옆에 둬요.',finish:'양팔을 옆으로 어깨 높이 부근까지 올려요.',cues:['어깨를 으쓱하지 않아요.','손목을 과하게 비틀지 않아요.','몸을 흔들지 않는 무게를 골라요.']},
 {id:'rear',name:'리어 델트 플라이',body:'어깨 · 등',equipment:'덤벨 · 인클라인 벤치',pose:'fly',match:['리어 델트','후면'],start:'벤치에 가슴을 지지하고 팔을 아래로 내려요.',finish:'팔꿈치 각도를 유지하며 양팔을 옆으로 벌려요.',cues:['머리와 척추를 자연스럽게 이어줘요.','승모근으로 과하게 으쓱하지 않아요.','높이보다 제어에 집중해요.']},
 {id:'yraise',name:'케이블 Y-레이즈',body:'어깨',equipment:'케이블',pose:'raise',match:['Y-레이즈','Y레이즈'],start:'가벼운 케이블을 잡고 몸통을 고정해요.',finish:'팔을 앞쪽 대각선 위로 들어 Y 모양을 만들어요.',cues:['가벼운 무게부터 시작해요.','허리를 젖히지 않아요.','어깨가 불편하면 범위를 줄여요.']},
 {id:'shrug',name:'슈러그',body:'승모',equipment:'덤벨 · 머신',pose:'shrug',match:['슈러그'],start:'몸을 세우고 양손의 무게를 옆에 둬요.',finish:'어깨를 위로 올렸다가 천천히 내려요.',cues:['어깨를 원으로 돌리지 않아요.','팔로 컬 동작을 하지 않아요.','목을 앞으로 내밀지 않아요.']},
 {id:'squat',name:'스쿼트',body:'하체',equipment:'바벨 · 핵 머신',pose:'squat',match:['스쿼트'],start:'발을 안정적으로 벌리고 몸통에 힘을 줘요.',finish:'엉덩이와 무릎을 함께 굽혔다가 바닥을 밀며 일어나요.',cues:['무릎은 발끝 방향을 따라가요.','뒤꿈치가 들리지 않는 범위로 내려가요.','처음에는 맨몸으로 익혀요.']},
 {id:'legpress',name:'레그 프레스',body:'하체',equipment:'머신',pose:'legpress',match:['레그프레스','레그 프레스'],start:'등과 골반을 패드에 붙이고 발판에 양발을 둬요.',finish:'무릎을 굽혀 발판을 받았다가 밀어내요.',cues:['골반이 말릴 만큼 깊게 내리지 않아요.','무릎을 세게 잠그지 않아요.','안전장치 사용법을 먼저 확인해요.']},
 {id:'legextend',name:'레그 익스텐션',body:'허벅지 앞',equipment:'머신',pose:'legextend',match:['레그 익스텐션'],start:'무릎 축을 기계 회전축에 맞추고 발목 앞에 패드를 둬요.',finish:'무릎을 펴 패드를 올렸다가 천천히 내려요.',cues:['엉덩이를 의자에서 들지 않아요.','무릎을 튕기며 펴지 않아요.','패드 위치와 의자 길이를 먼저 맞춰요.']},
 {id:'legcurl',name:'레그 컬',body:'허벅지 뒤',equipment:'머신',pose:'legcurl',match:['레그 컬','레그컬'],start:'기계 축에 무릎을 맞추고 발목 뒤쪽에 패드를 둬요.',finish:'무릎을 굽혀 패드를 당긴 뒤 천천히 펴요.',cues:['골반을 패드에 지지해요.','허리를 꺾어 들지 않아요.','기구의 조절 안내를 따라요.']},
 {id:'rdl',name:'루마니안 데드리프트',body:'허벅지 뒤 · 엉덩이',equipment:'덤벨 · 바벨',pose:'hinge',match:['데드리프트','RDL'],start:'무릎을 살짝 굽히고 무게를 허벅지 앞에 둬요.',finish:'엉덩이를 뒤로 보내며 숙였다가 엉덩이 힘으로 서요.',cues:['무게를 다리 가까이에 둬요.','허리를 둥글게 말지 않아요.','바닥에 닿는 것보다 편한 범위를 우선해요.']},
 {id:'curl',name:'이두 컬',body:'이두',equipment:'덤벨 · EZ바 · 프리처',pose:'curl',match:['컬'],start:'위팔을 안정시키고 손바닥을 위로 향하게 잡아요.',finish:'팔꿈치를 굽혀 올린 뒤 천천히 내려요.',cues:['몸을 뒤로 젖히며 들지 않아요.','손목을 꺾지 않아요.','프리처는 위팔을 패드에 지지해요.']},
 {id:'triceps',name:'삼두 익스텐션 · 푸시다운',body:'삼두',equipment:'케이블',pose:'extend',match:['푸시다운','푸시 다운','트라이셉스','오버헤드'],start:'위팔을 고정하고 팔꿈치가 굽혀진 위치에서 시작해요.',finish:'팔꿈치를 펴 손잡이를 움직인 뒤 제어하며 돌아와요.',cues:['푸시다운은 위팔을 몸 옆에 둬요.','오버헤드는 위팔을 머리 옆에 두는 별도 자세예요.','팔꿈치에 통증이 있으면 중단해요.']},
 {id:'jm',name:'클로즈 그립 프레스 · JM 프레스',body:'삼두',equipment:'바벨 · 벤치',pose:'bench',match:['클로즈','JM'],start:'벤치에 누워 일반 프레스보다 좁게 바를 잡아요.',finish:'팔꿈치를 조절하며 내렸다가 밀어 올려요.',cues:['JM 프레스는 별도 숙련 동작이라 지도 후 익혀요.','초보자는 머신이나 케이블로 대체할 수 있어요.','세이프티 바를 사용해요.']},
 {id:'core',name:'크런치 · 레그 레이즈',body:'복근',equipment:'케이블 · 철봉 · 매트',pose:'core',match:['크런치','레그 레이즈'],start:'몸통을 안정시키고 반동 없는 시작 자세를 잡아요.',finish:'크런치는 몸통을 말고, 레그 레이즈는 다리와 골반을 들어요.',cues:['서로 다른 동작이므로 기구별 자세를 확인해요.','목을 잡아당기지 않아요.','허리 통증 없이 조절되는 범위를 사용해요.']},
];
export function guideFor(name:string){const normalized=name.replaceAll(' ','').toLowerCase();return [...exerciseGuides].sort((a,b)=>Math.max(...b.match.map(s=>s.length))-Math.max(...a.match.map(s=>s.length))).find(g=>g.match.some(m=>normalized.includes(m.replaceAll(' ','').toLowerCase())));}
