import {z} from 'zod';
export const trainingProfileSchema=z.object({goal:z.enum(['hypertrophy','strength','consistency']),experience:z.enum(['beginner','intermediate','advanced']),daysPerWeek:z.number().int().min(1).max(7),adult:z.boolean()});
export type TrainingProfile=z.infer<typeof trainingProfileSchema>;
export const workoutSetSchema=z.object({id:z.string().min(1).max(60),kind:z.enum(['working','warmup','drop','failure']),weight:z.number().min(0).max(1500).nullable(),reps:z.number().int().min(1).max(100).nullable(),seconds:z.number().int().min(1).max(3600).nullable(),rir:z.number().int().min(0).max(10).nullable(),done:z.boolean()});
export const exerciseLogSchema=z.object({id:z.string().min(1).max(60),name:z.string().trim().min(1).max(60),plannedReps:z.number().int().min(1).max(100),timed:z.boolean(),convention:z.enum(['total','per_hand','machine','bodyweight','unknown']),equipmentLabel:z.string().trim().max(60),prescription:z.string().max(2000),superset:z.string().max(10).optional(),restSeconds:z.number().int().min(0).max(600).optional(),note:z.string().max(500).optional(),referenceMax:z.object({low:z.number().positive().max(3000),high:z.number().positive().max(3000),date:z.number().int().positive()}).optional(),sets:z.array(workoutSetSchema).min(1).max(30).refine(sets=>new Set(sets.map(s=>s.id)).size===sets.length)}).superRefine((e,c)=>{for(const s of e.sets)if(s.done&&(e.timed?s.seconds===null:s.reps===null))c.addIssue({code:'custom',message:'완료한 세트의 횟수 또는 시간을 입력해주세요.'});});
export const workoutStateSchema=z.object({exercises:z.array(exerciseLogSchema).min(1).max(30).refine(xs=>new Set(xs.map(e=>e.id)).size===xs.length),restSeconds:z.number().int().min(15).max(600),note:z.string().max(2000),discomfort:z.enum(['unreported','none','yes']),planBasis:z.object({sourceId:z.string().uuid(),sourceRevision:z.number().int().min(1),token:z.string().regex(/^[a-f0-9]{64}$/),createdAt:z.number().int().positive()}).optional(),durationMinutes:z.number().positive().max(1440).optional(),conditionsConfirmed:z.boolean().default(false)});
export type WorkoutSet=z.infer<typeof workoutSetSchema>;
export type ExerciseLog=z.infer<typeof exerciseLogSchema>;
export type WorkoutState=z.infer<typeof workoutStateSchema>;
export type Workout={id:string;user_id:string;crew_id:string;routine_id:string;routine_name:string;status:'active'|'completed'|'discarded';state:WorkoutState;revision:number;started_at:number;finished_at:number|null;updated_at:number};
export const loadLabels={total:'총 중량 kg',per_hand:'덤벨 한쪽 kg',machine:'기구 표시 kg',bodyweight:'맨몸 / 추가 중량 kg',unknown:'중량 기준 미설정'};
export function workoutTotals(workout:Workout){const exercises=workout.state.exercises;const sets=exercises.flatMap(e=>e.sets.filter(s=>s.done&&s.kind!=='warmup'));return {sets:sets.length,volume:exercises.reduce((sum,e)=>sum+e.sets.filter(s=>s.done&&s.kind!=='warmup'&&!e.timed&&s.weight!==null&&s.reps!==null).reduce((n,s)=>n+s.weight!*s.reps!,0),0),timedSeconds:exercises.filter(e=>e.timed).reduce((sum,e)=>sum+e.sets.filter(s=>s.done&&s.kind!=='warmup').reduce((n,s)=>n+(s.seconds??0),0),0),missingWeights:exercises.filter(e=>!e.timed&&e.convention!=='bodyweight').reduce((n,e)=>n+e.sets.filter(s=>s.done&&s.kind!=='warmup'&&s.weight===null).length,0)};}
